title = "DefaultMapDescriptions_ds1"
[maps]
m10_00_00_00 = "The Depths"
m10_01_00_00 = "Undead Burg / Undead Parish"
m10_02_00_00 = "Firelink Shrine"
m11_00_00_00 = "Painted World of Ariamis"
m12_00_00_00 = "Darkroot Garden / Darkroot Basin"
m12_01_00_00 = "Oolacile"
m13_00_00_00 = "The Catacombs"
m13_01_00_00 = "Tomb of the Giants"
m13_02_00_00 = "The Great Hollow / Ash Lake"
m14_00_00_00 = "Blighttown"
m14_01_00_00 = "Demon Ruins / Lost Izalith"
m15_00_00_00 = "Sen's Fortress"
m15_01_00_00 = "Anor Londo"
m16_00_00_00 = "New Londo Ruins / Valley of Drakes"
m17_00_00_00 = "Duke's Archives / Crystal Cave"
m18_00_00_00 = "Firelink Altar / Kiln of the First Flame"
m18_01_00_00 = "Northern Undead Asylum"