title = "DefaultESDDescriptions_sdt"
[maps]
[maps.m00_00_00_00]
t000001 = "Sculptor's Idol"
t000002 = "Reflection of Strength Idol"
t000010 = "Eavesdrop"
t000011 = "Eavesdrop (Alternate)"
t000012 = "Remnant"
[maps.m10_00_00_00]
t100210 = "Nogami Gensai"
t100340 = "Lady Butterfly (Phase 1)"
t100341 = "Lady Butterfly (Phase 2)"
[maps.m11_00_00_00]
t110010 = "Offering Box"
t110100 = "The Sculptor"
t110101 = "Buddha Statue"
t110102 = "Demon of Hatred"
t110110 = "Remnant (Kuro and Emma)"
t110111 = "Remnant (Kuro and Genichiro)"
t110130 = "Hanbei the Undying"
t110160 = "Inosuke Nogami's Mother"
t110171 = "Anayama the Peddler"
t110181 = "Inosuke Nogami"
t110230 = "Emma"
t110240 = "Tengu of Ashina"
t110260 = "Kotaro"
t110350 = "Gyobu Oniwa"
t110400 = "Old Priestess"
t110410 = "Crow's Bed Memorial Mob"
t110420 = "Battlefield Memorial Mob"
t110470 = "Fujioka the Info Broker"
t110600 = "Eavesdrop (soldiers near Chained Ogre)"
t110601 = "Eavesdrop (soldiers near Gyobu Oniwa)"
t110602 = "Eavesdrop (soldiers after Naomori Kawarada)"
t110603 = "Eavesdrop (soldier mourning his horse)"
t110700 = "Injured Ashina Soldier (castle bridge)"
t110701 = "Injured Red Guard (before demon warp)"