title = "DefaultESDDescriptions_nr"
[maps]
[maps.m00_00_00_00]
t000001000 = "Site of Grace"
[maps.m10_00_00_00]
t600001000 = "Roundtable"
t100401000 = "Priestess"
t101001000 = "Iron Menial"
t200201000 = "Guardian"
t618001000 = "Collector Signboard"
t200601000 = "Revenant"
t200501000 = "Raider"
t181301000 = "Executor (Remembrance end dialogue)"
t180201000 = "Guardian (Executor Remembrance)"
t110701000 = "Recluse (Wylder Remembrance)"
t180401000 = "Priestess (Executor Remembrance)"
t110401000 = "Duchess (Wylder Remembrance)"
t140101000 = "Wylder (Duchess Remembrance)"
t150301000 = "Ironeye (Raider Remembrance)"
t200701000 = "Recluse"
t140601000 = "Revenant (Duchess Remembrance)"
t200101000 = "Wylder"
t171101000 = "Witch of the Wheel"
t660001000 = "Revenant (Phantom)"
t140501000 = "Raider (Duchess Remembrance)"
t130401000 = "Priestess (Ironeye Remembrance)"
t200301000 = "Ironeye"
t200801000 = "Executor"
t131401000 = "Traitor (Ironeye Remembrance)"
t120701000 = "Recluse (Guardian Remembrance)"
t120501000 = "Raider (Guardian Remembrance)"
t160401000 = "Duchess (Revenant Remembrance)"
t160201000 = "Guardian (Revenant Remembrance)"
t160101000 = "Wylder (Revenant Remembrance)"
t160701000 = "Recluse (Revenant Remembrance)"
t601001000 = "Character Selection"
t604001000 = "Relic Rites Altar"
t605001000 = "Small Jar Bazaar"
t603001000 = "Visual Codex"
t606001000 = "Journal"
t151001000 = "Iron Menial (Raider Remembrance)"
t155001000 = "Monument (Raider Remembrance)"
t155101000 = "Raider (dialogue at monument)"
t145001000 = "Bread plate (Duchess Remembrance)"
t610001000 = "Various written notes"
t607001000 = "Sparring Equipment"
t609001000 = "Sparring Settings"
t115001000 = "Earring (Wylder Remembrance)"
t185001000 = "Painting (Executor Remembrance)"
t115101000 = "Hold up both earrings (Wylder Remembrance)"
t615001000 = "Change Garb"
t165001000 = "Bench (Revenant Remembrance)"
t115801000 = "Crypt statue"
t115901000 = "Crypt coffin 1"
t617001000 = "Bed (Pass time)"
t115301000 = "Book pile near Visual Codex (Wylder Remembrance)"
t115401000 = "Bookshelf near Visual Codex (Wylder Remembrance)"
t115501000 = "Book pile near Jar Bazaar (Wylder Remembrance)"
t115601000 = "Note on Iron Menial workdesk (Wylder Remembrance)"
t145101000 = "Rocks near Roundtable (Duchess Remembrance)"
t145201000 = "Kitchen (Duchess Remembrance)"
t115701000 = "Hold up earring (Wylder Remembrance)"
t145301000 = "Bless iron coin (Duchess Remembrance)"
t145401000 = "Scribble on Roundtable (Duchess Remembrance)"
t175101000 = "Bed (Recluse Remembrance)"
t145501000 = "Note at Iron Menial workdesk (Duchess Remembrance)"
t175201000 = "Note on Roundtable (Recluse Remembrance)"
t125001000 = "Scrap on Roundtable (Guardian Remembrance)"
t125101000 = "Bookshelf near Visual Codex (Guardian Remembrance)"
t135001000 = "Note near crypt stairs (Ironeye Remembrance)"
t650001000 = "Conclude Remembrance"
t105001000 = "Book pile near Visual Codex"
t105101000 = "Bookshelf near Visual Codex 1"
t105201000 = "Book pile near Jar Bazaar"
t105301000 = "Bookshelf near Visual Codex 2"
t116001000 = "Crypt coffin 2"
t201001000 = "Iron Menial (workshop)"
t141001000 = "Iron Menial (Duchess Remembrance)"
t111001000 = "Iron Menial (Wylder Remembrance)"
t181001000 = "Iron Menial (Executor Remembrance)"
t171001000 = "Iron Menial (Recluse Remembrance)"
t121001000 = "Iron Menial (Guardian Remembrance)"
t161001000 = "Iron Menial (Revenant Remembrance)"
t121201000 = "Wandering Merchant (Guardian Remembrance)"
[maps.m11_00_00_00]
t616001100 = "Long-limbed Man"
[maps.m12_00_00_00]
t800001200 = "Spirit Shelter Merchant"
t602001200 = "Smithing Table"
[maps.m13_00_00_00]
t181301300 = "Crucible Knight"
[maps.m15_00_00_00]
t167101500 = "Revenant Doll"
t167301500 = "Portrait"
[maps.m19_00_00_00]
t703001900 = "Libra (Boss)"
[maps.m30_00_00_00]
t800003000 = "Wandering Merchant"
[maps.m32_00_00_00]
t602003200 = "Smithing Table"
t800003200 = "Wandering Merchant"
[maps.m35_90_00_00]
t210003590 = "Margit (Tutorial)"
t211003590 = "Margit (Tutorial, defeated)"
[maps.m37_90_00_00]
t903003790 = "Special Merchant"
[maps.m41_00_00_00]
t900004100 = "Church Altar"
[maps.m41_01_00_00]
t900004101 = "Church Altar"
[maps.m41_30_00_00]
t900004130 = "Church Altar"
[maps.m45_55_00_00]
t703004555 = "Libra (Remembrance)"
[maps.m60_00_00_00]
t167006000 = "Black Pool"
t703006000 = "Libra (Overworld)"
t210006000 = "Margit (Raid)"
t602006000 = "Smithing Table 1"
t602016000 = "Smithing Table 2"
t602026000 = "Smithing Table 3"
t602036000 = "Smithing Table 4"
t602046000 = "Smithing Table 5"
t608006000 = "Weapon Duplication Coffin"
t701006000 = "Legendary Smithing Table"
t800006000 = "Wandering Merchant"
t900006000 = "Church Altar 1"
t900016000 = "Church Altar 2"
t900026000 = "Church Altar 3"
t900036000 = "Church Altar 4"
t900306000 = "Church Altar 5"
t900506000 = "Church Altar 6"
t903006000 = "Special Merchant"