title = "DefaultESDDescriptions_ds1"
[maps]
[maps.m10_00_00_00]
t100000 = "The Depths Bonfire"
t100613 = "Laurentius of the Great Swamp"
t100626 = "Domhnall of Zena"
[maps.m10_01_00_00]
t100101 = "Undead Parish Bridge Bonfire"
t100102 = "Undead Burg Bonfire"
t100104 = "Undead Parish Blacksmith Bonfire"
t101600 = "Solaire of Astora"
t101604 = "Griggs of Vinheim"
t101607 = "Rhea of Thorolund"
t101619 = "Andre of Astora"
t101623 = "Male Undead Merchant"
t101630 = "Lautrec of Carim"
t101637 = "Oswald of Carim"
t101648 = "Altar of Sunlight"
[maps.m10_02_00_00]
t100200 = "Firelink Shrine Bonfire"
t102603 = "Big Hat Logan"
t102604 = "Griggs of Vinheim"
t102606 = "Anastacia of Astora"
t102607 = "Rhea of Thorolund"
t102608 = "Petrus of Thorolund"
t102609 = "Vince of Thorolund"
t102610 = "Nico of Thorolund"
t102613 = "Laurentius of the Great Swamp"
t102618 = "Ingward"
t102624 = "Female Undead Merchant"
t102626 = "Domhnall of Zena"
t102627 = "Crestfallen Warrior"
t102628 = "Siegmeyer of Catarina"
t102629 = "Sieglinde of Catarina"
t102630 = "Lautrec of Carim"
t102632 = "Patches the Hyena"
t102633 = "Kingseeker Frampt"
[maps.m11_00_00_00]
t110636 = "Crossbreed Priscilla"
t110000 = "Painted World of Ariamis Bonfire"
[maps.m12_00_00_00]
t120001 = "Darkroot Garden Bonfire"
t120605 = "Dusk of Oolacile (inside golem)"
t120631 = "Shiva of the East"
t120638 = "Alvina"
t120642 = "Shiva's Bodyguard"
t120663 = "Dusk of Oolacile (summoned)"
[maps.m12_01_00_00]
t121000 = "Sanctuary Garden Bonfire"
t121001 = "Oolacile Sanctuary Bonfire"
t121002 = "Oolacile Township Bonfire"
t121003 = "Manus, Father of the Abyss Bonfire"
t121004 = "Chasm of the Abyss Bonfire"
t121200 = "Battle of Stoicism (Leaderboard)"
t121661 = "Battle of Stoicism (Duel: Ruins)"
t121662 = "Battle of Stoicism (Duel: Dais)"
t121663 = "Battle of Stoicism (Team: Ruins)"
t121664 = "Battle of Stoicism (Team: Dais)"
t121665 = "Battle of Stoicism (Deathmatch: Ruins)"
t121666 = "Battle of Stoicism (Deathmatch: Dais)"
t121670 = "Dusk of Oolacile"
t121672 = "Hawkeye Gough"
t121673 = "Marvelous Chester"
t121674 = "Lord's Blade Ciaran"
t121675 = "Elizabeth"
[maps.m13_00_00_00]
t130000 = "Upper Catacombs Bonfire"
t130001 = "Inner Catacombs Bonfire"
t130620 = "Blacksmith Vamos"
t130632 = "Patches the Hyena"
[maps.m13_01_00_00]
t131000 = "Lower Tomb of the Giants Bonfire"
t131001 = "Upper Tomb of the Giants Bonfire"
t131010 = "Tomb of the Gravelord Bonfire"
t131607 = "Rhea of Thorolund"
t131632 = "Patches the Hyena"
t131646 = "Gravelord Nito"
[maps.m13_02_00_00]
t132000 = "Stone Dragon Bonfire"
t132001 = "Ash Lake Bonfire"
t132002 = "Great Hollow Bonfire"
t132629 = "Sieglinde of Catarina"
t132647 = "Everlasting Dragon"
[maps.m14_00_00_00]
t140000 = "Demon Ruins Bonfire"
t140001 = "Lower Blighttown Bonfire"
t140002 = "Upper Blighttown Bonfire"
t140614 = "Chaos Witch Quelaag"
t140615 = "The Fair Lady"
t140616 = "Eingyi of the Great Swamp"
t140617 = "Quelana of Izalith"
t140628 = "Siegmeyer of Catarina"
t140631 = "Shiva of the East"
t140642 = "Shiva's Bodyguard"
[maps.m14_01_00_00]
t141000 = "Lost Izalith Bonfire"
t141001 = "Upper Demon Ruins Bonfire"
t141002 = "Lower Demon Ruins Bonfire"
t141003 = "After Demon Firesage Bonfire"
t141004 = "After Centipede Demon Bonfire"
t141628 = "Siegmeyer of Catarina"
t141600 = "Solaire of Astora (After Centipede)"
t141658 = "Solaire of Astora (Hostile)"
[maps.m15_00_00_00]
t150001 = "Sen's Fortress Bonfire"
t150603 = "Big Hat Logan"
t150625 = "Crestfallen Merchant"
t150628 = "Siegmeyer of Catarina"
[maps.m15_01_00_00]
t151000 = "Anor Londo Bonfire"
t151001 = "Inner Anor Londo Bonfire"
t151002 = "Darkmoon Tomb Bonfire"
t151010 = "Chamber of the Princess Bonfire"
t151600 = "Solaire of Astora"
t151601 = "Darkmoon Knightess"
t151611 = "Gwynevere, Princess of Sunlight"
t151612 = "Darksun Gwyndolin (Covenant Leader)"
t151621 = "Giant Blacksmith"
t151628 = "Siegmeyer of Catarina"
t151630 = "Lautrec of Carim"
[maps.m16_00_00_00]
t160001 = "Darkroot Basin Bonfire"
t160010 = "The Abyss Bonfire"
t160618 = "Ingward"
t160622 = "Rickert of Vinheim"
t160634 = "Darkstalker Kaathe"
[maps.m17_00_00_00]
t170000 = "Duke's Archives Balcony Bonfire"
t170001 = "Prison Tower Bonfire"
t170002 = "Duke's Archives Entrance Bonfire"
t170010 = "Crystal Cave Bonfire"
t170603 = "Big Hat Logan"
t170629 = "Sieglinde of Catarina"
[maps.m18_00_00_00]
t180100 = "Firelink Altar Bonfire"
t180633 = "Kingseeker Frampt"
t180634 = "Darkstalker Kaathe"
[maps.m18_01_00_00]
t181000 = "Undead Asylum Courtyard Bonfire"
t181001 = "Undead Asylum Sewer Bonfire"
t181602 = "Oscar of Astora"
t181645 = "Snuggly the Crow"