title = "DefaultESDDescriptions_ds1r"
[maps]
[maps.m10_00_00_00]
100000 = "The Depths Bonfire"
100613 = "Laurentius of the Great Swamp"
100626 = "Domhnall of Zena"
[maps.m10_01_00_00]
100101 = "Undead Parish Bridge Bonfire"
100102 = "Undead Burg Bonfire"
100104 = "Undead Parish Blacksmith Bonfire"
101600 = "Solaire of Astora"
101604 = "Griggs of Vinheim"
101607 = "Rhea of Thorolund"
101619 = "Andre of Astora"
101623 = "Male Undead Merchant"
101630 = "Lautrec of Carim"
101637 = "Oswald of Carim"
101648 = "Altar of Sunlight"
[maps.m10_02_00_00]
100200 = "Firelink Shrine Bonfire"
102603 = "Big Hat Logan"
102604 = "Griggs of Vinheim"
102606 = "Anastacia of Astora"
102607 = "Rhea of Thorolund"
102608 = "Petrus of Thorolund"
102609 = "Vince of Thorolund"
102610 = "Nico of Thorolund"
102613 = "Laurentius of the Great Swamp"
102618 = "Ingward"
102624 = "Female Undead Merchant"
102626 = "Domhnall of Zena"
102627 = "Crestfallen Warrior"
102628 = "Siegmeyer of Catarina"
102629 = "Sieglinde of Catarina"
102630 = "Lautrec of Carim"
102632 = "Patches the Hyena"
102633 = "Kingseeker Frampt"
[maps.m11_00_00_00]
110636 = "Crossbreed Priscilla"
110000 = "Painted World of Ariamis Bonfire"
[maps.m12_00_00_00]
120001 = "Darkroot Garden Bonfire"
120605 = "Dusk of Oolacile (inside golem)"
120631 = "Shiva of the East"
120638 = "Alvina"
120642 = "Shiva's Bodyguard"
120663 = "Dusk of Oolacile (summoned)"
[maps.m12_01_00_00]
121000 = "Sanctuary Garden Bonfire"
121001 = "Oolacile Sanctuary Bonfire"
121002 = "Oolacile Township Bonfire"
121003 = "Manus, Father of the Abyss Bonfire"
121004 = "Chasm of the Abyss Bonfire"
121200 = "Battle of Stoicism (Leaderboard)"
121661 = "Battle of Stoicism (Duel: Ruins)"
121662 = "Battle of Stoicism (Duel: Dais)"
121663 = "Battle of Stoicism (Team: Ruins)"
121664 = "Battle of Stoicism (Team: Dais)"
121665 = "Battle of Stoicism (Deathmatch: Ruins)"
121666 = "Battle of Stoicism (Deathmatch: Dais)"
121670 = "Dusk of Oolacile"
121672 = "Hawkeye Gough"
121673 = "Marvelous Chester"
121674 = "Lord's Blade Ciaran"
121675 = "Elizabeth"
[maps.m13_00_00_00]
130000 = "Upper Catacombs Bonfire"
130001 = "Inner Catacombs Bonfire"
130002 = "Lower Catacombs Bonfire"
130620 = "Blacksmith Vamos"
130632 = "Patches the Hyena"
[maps.m13_01_00_00]
131000 = "Lower Tomb of the Giants Bonfire"
131001 = "Upper Tomb of the Giants Bonfire"
131010 = "Tomb of the Gravelord Bonfire"
131607 = "Rhea of Thorolund"
131632 = "Patches the Hyena"
131646 = "Gravelord Nito"
[maps.m13_02_00_00]
132000 = "Stone Dragon Bonfire"
132001 = "Ash Lake Bonfire"
132002 = "Great Hollow Bonfire"
132629 = "Sieglinde of Catarina"
132647 = "Everlasting Dragon"
[maps.m14_00_00_00]
140000 = "Demon Ruins Bonfire"
140001 = "Lower Blighttown Bonfire"
140002 = "Upper Blighttown Bonfire"
140614 = "Chaos Witch Quelaag"
140615 = "The Fair Lady"
140616 = "Eingyi of the Great Swamp"
140617 = "Quelana of Izalith"
140628 = "Siegmeyer of Catarina"
140631 = "Shiva of the East"
140642 = "Shiva's Bodyguard"
[maps.m14_01_00_00]
141000 = "Lost Izalith Bonfire"
141001 = "Upper Demon Ruins Bonfire"
141002 = "Lower Demon Ruins Bonfire"
141003 = "After Demon Firesage Bonfire"
141004 = "After Centipede Demon Bonfire"
141628 = "Siegmeyer of Catarina"
141600 = "Solaire of Astora (After Centipede)"
141658 = "Solaire of Astora (Hostile)"
[maps.m15_00_00_00]
150001 = "Sen's Fortress Bonfire"
150603 = "Big Hat Logan"
150625 = "Crestfallen Merchant"
150628 = "Siegmeyer of Catarina"
[maps.m15_01_00_00]
151000 = "Anor Londo Bonfire"
151001 = "Inner Anor Londo Bonfire"
151002 = "Darkmoon Tomb Bonfire"
151010 = "Chamber of the Princess Bonfire"
151600 = "Solaire of Astora"
151601 = "Darkmoon Knightess"
151611 = "Gwynevere, Princess of Sunlight"
151612 = "Darksun Gwyndolin (Covenant Leader)"
151621 = "Giant Blacksmith"
151628 = "Siegmeyer of Catarina"
151630 = "Lautrec of Carim"
[maps.m16_00_00_00]
160001 = "Darkroot Basin Bonfire"
160010 = "The Abyss Bonfire"
160618 = "Ingward"
160622 = "Rickert of Vinheim"
160634 = "Darkstalker Kaathe"
[maps.m17_00_00_00]
170000 = "Duke's Archives Balcony Bonfire"
170001 = "Prison Tower Bonfire"
170002 = "Duke's Archives Entrance Bonfire"
170010 = "Crystal Cave Bonfire"
170603 = "Big Hat Logan"
170629 = "Sieglinde of Catarina"
[maps.m18_00_00_00]
180100 = "Firelink Altar Bonfire"
180633 = "Kingseeker Frampt"
180634 = "Darkstalker Kaathe"
[maps.m18_01_00_00]
181000 = "Undead Asylum Courtyard Bonfire"
181001 = "Undead Asylum Sewer Bonfire"
181602 = "Oscar of Astora"
181645 = "Snuggly the Crow"