title = "DefaultESDDescriptions_ds3"
[maps]
[maps.m30_00_00_00]
t300000 = "High Wall of Lothric Bonfire"
t300001 = "Oceiros, the Consumed King Bonfire"
t300002 = "Vordt of the Boreal Valley Bonfire"
t300003 = "Dancer of the Boreal Valley Bonfire"
t300004 = "Tower on the Wall Bonfire"
t300020 = "Path of the Dragon Gesture Pickup"
t300220 = "Greirat of the Undead Settlement"
t300324 = "Oceiros, the Consumed King"
t300330 = "Emma, High Priestess of Lothric Castle"
[maps.m30_01_00_00]
t301000 = "Lothric Castle Bonfire"
t301001 = "Dragonslayer Armour Bonfire"
t301002 = "Dragon Barracks Bonfire"
t301020 = "Altar of Sunlight"
[maps.m31_00_00_00]
t310000 = "Undead Settlement Bonfire"
t310001 = "Pit of Hollows Bonfire"
t310002 = "Cliff Underside Bonfire"
t310003 = "Dilapidated Bridge Bonfire"
t310004 = "Foot of the High Wall Bonfire"
t310020 = "Sacrificial Altar"
t310021 = "Velka, the Goddess of Sin"
t310150 = "Yoel of Londor"
t310180 = "Sirris of the Sunless Realms"
t310240 = "Cornyx of the Great Swamp"
t310260 = "Irina of Carim"
t310270 = "Eygon of Carim"
t310310 = "Siegward of Catarina (lift)"
t310311 = "Siegward of Caterina (ledge)"
t310380 = "Talking Cage Hollow"
t310410 = "Holy Knight Hodrick"
t310610 = "Giant Archer"
[maps.m32_00_00_00]
t320000 = "Archdragon Peak Bonfire"
t320001 = "Nameless King Bonfire"
t320002 = "Great Belfry Bonfire"
t320003 = "Dragon-Kin Mausoleum Bonfire"
[maps.m33_00_00_00]
t330000 = "Halfway Fortress Bonfire"
t330001 = "Abyss Watchers Bonfire"
t330002 = "Crystal Sage Bonfire"
t330003 = "Farron Keep Bonfire"
t330004 = "Keep Ruins Bonfire"
t330005 = "Old Wolf of Farron Bonfire"
t330006 = "Road of Sacrifices Bonfire"
t330007 = "Crucifixion Woods Bonfire"
t330008 = "Farron Keep Perimeter Bonfire"
t330020 = "Old Wolf of Farron"
t330170 = "Hawkwood the Deserter"
t330230 = "Orbeck of Vinheim"
t330290 = "Anri of Astora (male)"
t330295 = "Anri of Astora (female)"
t330360 = "Horace the Hushed"
[maps.m34_01_00_00]
t341000 = "Twin Princes Bonfire"
t341001 = "Grand Archives Bonfire"
t341320 = "Lothric, Younger Prince"
[maps.m35_00_00_00]
t350000 = "Cleansing Chapel Bonfire"
t350001 = "Rosaria's Bed Chamber Bonfire"
t350002 = "Deacons of the Deep Bonfire"
t350003 = "Cathedral of the Deep Bonfire"
t350020 = "Rosaria, Mother of Rebirth"
t350190 = "Ringfinger Leonhard"
t350300 = "Unbreakable Patches (door side 1)"
t350301 = "Unbreakable Patches (Rosaria side)"
t350302 = "Unbreakable Patches (door side 2)"
t350310 = "Siegward of Catarina"
t350510 = "Slave Knight Gael"
[maps.m37_00_00_00]
t370000 = "Church of Yorshka Bonfire"
t370001 = "Pontiff Sulyvahn Bonfire"
t370002 = "Aldrich, Devourer of Gods Bonfire"
t370003 = "Anor Londo Bonfire"
t370004 = "Central Irithyll Bonfire"
t370005 = "Distant Manor Bonfire"
t370006 = "Water Reserve Bonfire"
t370007 = "Irithyll of the Boreal Valley Bonfire"
t370008 = "Prison Tower Bonfire"
t370020 = "Archdeacon McDonnell"
t370160 = "Company Captain Yorshka"
t370180 = "Sirris of the Sunless Realms"
t370190 = "Ringfinger Leonhard"
t370290 = "Anri of Astora (male) (Church of Yorshka)"
t370291 = "Anri of Astora (male) (Aldrich)"
t370295 = "Anri of Astora (female) (Church of Yorshka)"
t370296 = "Anri of Astora (female) (Aldrich)"
t370310 = "Siegward of Catarina"
t370400 = "Londor Assassin (Church of Yorshka)"
t370401 = "Londor Assassin (Darkmoon Tomb)"
[maps.m38_00_00_00]
t380000 = "High Lord Wolnir Bonfire"
t380001 = "Abandoned Tomb Bonfire"
t380002 = "Old King's Antechamber Bonfire"
t380003 = "Demon Ruins Bonfire"
t380004 = "Old Demon King Bonfire"
t380005 = "Unused Bonfire"
t380006 = "Catacombs of Carthus Bonfire"
t380290 = "Anri of Astora (male) (upper catacombs)"
t380291 = "Anri of Astora (male) (near Wolnir)"
t380295 = "Anri of Astora (female) (upper catacombs)"
t380296 = "Anri of Astora (female) (near Wolnir)"
[maps.m39_00_00_00]
t390000 = "Irithyll Dungeon Bonfire"
t390001 = "Yhorm the Giant Bonfire"
t390002 = "Profaned Capital Bonfire"
t390250 = "Karla"
t390310 = "Siegward of Catarina (cell)"
t390311 = "Siegward of Catarina (Yhorm)"
[maps.m40_00_00_00]
t400000 = "Firelink Shrine Bonfire"
t400001 = "Cemetery of Ash Bonfire"
t400002 = "Iudex Gundyr Bonfire"
t400003 = "Untended Graves Bonfire"
t400004 = "Champion Gundyr Bonfire"
t400120 = "Fire Keeper"
t400130 = "Ludleth of Courland (alive)"
t400131 = "Ludleth of Courland (ashes)"
t400140 = "Yuria of Londor"
t400150 = "Yoel of Londor"
t400170 = "Hawkwood the Deserter (Firelink Shrine)"
t400171 = "Hawkwood the Deserter (grave)"
t400172 = "Legion Etiquette Gesture Pickup"
t400180 = "Sirris of the Sunless Realms"
t400190 = "Ringfinger Leonhard"
t400200 = "Blacksmith Andre"
t400210 = "Shrine Handmaid (Firelink Shrine)"
t400211 = "Shrine Handmaid (Untended Graves)"
t400220 = "Greirat of the Undead Settlement"
t400230 = "Orbeck of Vinheim"
t400240 = "Cornyx of the Great Swamp"
t400250 = "Karla"
t400260 = "Irina of Carim (Firelink Shrine)"
t400261 = "Irina of Carim (outside)"
t400262 = "Irina of Carim (fire keeper tomb)"
t400270 = "Eygon of Carim (Firelink Shrine)"
t400271 = "Eygon of Carim (outside)"
t400290 = "Anri of Astora (male)"
t400295 = "Anri of Astora (female)"
t400300 = "Unbreakable Patches (lift)"
t400301 = "Unbreakable Patches (Firelink Shrine)"
t400360 = "Horace the Hushed"
t400390 = "Pickle Pee, Pump-a-Rum"
[maps.m41_00_00_00]
t410001 = "Kiln of the First Flame Bonfire"
t410002 = "The First Flame"
t410010 = "Flameless Shrine Bonfire"
t410120 = "Fire Keeper"
t410990 = "Begin New Journey Prompt"
[maps.m45_00_00_00]
t450000 = "Sister Friede Bonfire"
t450001 = "Snowfield Bonfire"
t450002 = "Rope Bridge Cave Bonfire"
t450003 = "Corvian Settlement bonfire"
t450004 = "Snowy Mountain Pass Bonfire"
t450005 = "Ariandel Chapel Bonfire"
t450006 = "Champion's Gravetender Bonfire"
t450007 = "Depths of the Painting Bonfire"
t450520 = "Sir Vilhelm (Ariandel Chapel)"
t450521 = "Sir Vilhelm (settlement house)"
t450530 = "The Painter (settlement house)"
t450531 = "The Painter (Ariandel Chapel)"
t450540 = "Forlorn Corvian Settler (inside)"
t450541 = "Forlorn Corvian Settler (outside)"
t450550 = "Sister Friede (Ariandel Chapel)"
t450551 = "Sister Friede (boss)"
t450552 = "Blackflame Friede"
t450560 = "Father Ariandel (passive)"
t450561 = "Father Ariandel (boss)"
t450590 = "Drowsy Forlorn"
[maps.m50_00_00_00]
t500000 = "The Demon Prince Bonfire"
t500001 = "The Dreg Heap Bonfire"
t500002 = "Earthen Peak Ruins Bonfire"
t500003 = "Within the Earthen Peak Ruins Bonfire"
t500004 = "Unused Bonfire"
t500730 = "Amnesiac Lapp (Lothric Castle ruins)"
t500731 = "Amnesiac Lapp (Earthen Peak Ruins 1)"
t500732 = "Amnesiac Lapp (Earthen Peak Ruins 2)"
t500760 = "Stone-humped Hag"
[maps.m51_00_00_00]
t510000 = "Church of Filianore Bonfire"
t510001 = "Darkeater Midir Bonfire"
t510002 = "Mausoleum Lookout Bonfire"
t510003 = "Ringed Inner Wall Bonfire"
t510004 = "Ringed City Streets Bonfire"
t510005 = "Shared Grave Bonfire"
t510020 = "Divine Spear Monument"
t510021 = "Purging Monument"
t510730 = "Amnesiac Lapp (Ringed Inner Wall)"
t510731 = "Amnesiac Lapp (Above Ringed City Streets)"
t510732 = "Amnesiac Lapp (near Shared Grave)"
t510740 = "Shira, Knight of Filianore"
t510750 = "Locust Preacher (near Ringed Inner Wall)"
t510751 = "Locust Preacher (above near swamp)"
t510752 = "Locust Preacher (near Ringed City Streets)"
t510770 = "Pygmy Lord"
t510780 = "Judicator Argo"
[maps.m51_01_00_00]
t511000 = "Slave Knight Gael Bonfire"
t511001 = "Filianore's Rest Bonfire"
t511740 = "Shira, Knight of Filianore"
t511770 = "Pygmy Lord"