title = "DefaultESDDescriptions_bb"
[maps]
[maps.m21_00_00_00]
t210000 = "Yharnam Headstone"
t210001 = "Frontier Headstone"
t210002 = "Unseen Headstone"
t210003 = "Nightmare Headstone"
t210010 = "(Unused)"
t210020 = "(Unused)"
t210030 = "(Unused)"
t210040 = "(Unused)"
t210050 = "Makeshift Altar"
t210060 = "First Ritual Altar"
t210070 = "Second Ritual Altar"
t210080 = "Third Ritual Altar"
t210090 = "Fourth Ritual Altar"
t210100 = "Fifth Ritual Altar"
t210110 = "Final Ritual Altar"
t210140 = "(Unused)"
t210141 = "(Unused)"
t210200 = "(Unused)"
t210304 = "Plain Doll"
t210305 = "Gherman (Wheelchair Bound)"
t210306 = "Gherman (Boss)"
t210600 = "DS1 Undead Shopkeeper (Unused)"
t210610 = "(Unused)"
t210611 = "(Unused)"
t210612 = "(Unused)"
t210613 = "(Unused)"
t210614 = "(Unused)"
t210615 = "(Unused)"
t210616 = "(Unused)"
t210617 = "(Unused)"
t210618 = "(Unused)"
t210619 = "(Unused)"
t210630 = "(Unused)"
t210631 = "(Unused)"
t210632 = "(Unused)"
t210633 = "(Unused)"
t210634 = "(Unused)"
t210635 = "(Unused)"
t210650 = "(Unused)"
t210690 = "(Unused)"
t210691 = "Bath Messenger Shop"
t210692 = "Workshop"
t210693 = "Storage Chest"
t210694 = "Starting Gift Messengers 1"
t210695 = "Starting Gift Messengers 2"
t210696 = "Change Appearance Mirror (Unused)"
t210697 = "Messenger Stump"
t210698 = "Insight Messenger Shop"
t210699 = "Memory Altar"
t210700 = "Plain Doll Prototype"
t210701 = "(Unused)"
t210702 = "(Unused)"
t210703 = "(Unused)"
t210704 = "(Unused)"
t210705 = "(Unused)"
t210706 = "(Unused)"
t210710 = "(Unused)"
t210711 = "(Unused)"
t210712 = "(Unused)"
t210713 = "(Unused)"
t210714 = "(Unused)"
t210715 = "(Unused)"
t210716 = "(Unused)"
t210720 = "Messenger Gift Notebook"
t210721 = "Hunter's Nightmare Headstone"
t210900 = "(Unused)"
[maps.m21_01_00_00]
t211000 = "Abandoned Old Workshop (Lamp)"
[maps.m22_00_00_00]
t220000 = "Hemwick Charnel Lane (Lamp)"
t220001 = "Watches Abode (Lamp)"
t220300 = "Micolash (Prototype)"
t220307 = "Micolash (Prototype) 2"
t220374 = "(Unused)"
t220464 = "Yharnam Resident Female (Window) 5"
[maps.m23_00_00_00]
t230000 = "Old Yharnam (Lamp)"
t230001 = "Church of the Good Chalice (Lamp)"
t230002 = "Graveyard of the Darkbeast (Lamp)"
t230300 = "Old Yharnam Survivor (Unused)"
t230323 = "Djura"
[maps.m24_00_00_00]
t240000 = "Cathedral Ward (Lamp)"
t240001 = "Grand Cathedral (Lamp)"
t240002 = "Lamp (Unused)"
t240003 = "Lamp (Unused)"
t240118 = "(Unused)"
t240215 = "Bigoted Old Man (Home)"
t240217 = "Suspicious Beggar (Beast Form)"
t240218 = "Arianna, Woman of Pleasure (Home)"
t240312 = "Chapel Dweller"
t240315 = "Bigoted Old Man (Chapel)"
t240316 = "Lonely Old Dear"
t240317 = "Afflicted Beggar (Unused)"
t240318 = "Arianna, Woman of Pleasure (Chapel)"
t240322 = "Adella, Nun of the Healing Church"
t240325 = "Eileen the Crow"
t240326 = "Vicar Amelia (Prayer)"
t240327 = "Gatekeeper to the Forbidden Woods"
t240333 = "Alfred, Hunter of Vilebloods (Old Yharnam Side)"
t240334 = "Adella, Nun of the Healing Church (Blood Moon)"
t240335 = "Arianna, Woman of Pleasure (Blood Moon)"
t240336 = "Arianna, Woman of Pleasure (Blood Moon post One Reborn)"
t240337 = "Arianna, Woman of Pleasure (Birth/Unused)"
t240338 = "Afflicted Beggar"
t240339 = "Adella, Nun of the Healing Church (Killed Arianna/Night)"
t240340 = "Adella, Nun of the Healing Church (Killed Arianna/Blood Moon)"
t240341 = "Eileen the Crow (Hostile at the Church)"
t240342 = "Eileen the Crow (Dying on the stairs)"
t240343 = "Alfred, Hunter of Vilebloods (Forbidden Woods Side)"
t240351 = "(Unused)"
t240353 = "(Unused)"
t240362 = "(Unused)"
t240363 = "(Unused)"
t240364 = "(Unused)"
t240372 = "(Unused)"
t240373 = "(Unused)"
t240442 = "Yharnam Resident Male (Window) 3"
t240443 = "Yharnam Resident Male (Window) 4"
t240444 = "Yharnam Resident Male (Window) 5"
t240462 = "Yharnam Resident Female (Window) 3"
t240463 = "Yharnam Resident Female (Window) 4"
t240504 = "Chapel Dweller (Unused)"
t240630 = "(Unused)"
t240700 = "(Unused)"
[maps.m24_01_00_00]
t241000 = "1st Floor Sickroom (Lamp)"
t241001 = "Central Yharnam (Lamp)"
t241002 = "Great Bridge (Lamp)"
t241003 = "Tomb of Oedon (Lamp)"
t241190 = "(Unused)"
t241300 = "Father Gascoigne Alpha (Boss)"
t241310 = "Father Gascoigne Alpha (Boss)"
t241313 = "Iosefka"
t241314 = "Impostor Iosefka (Behind the door)"
t241315 = "Bigoted Old Man (Unused)"
t241316 = "Lonely Old Dear (Window)"
t241318 = "Arianna, Woman of Pleasure (Birth)"
t241319 = "Gilbert, Critically Ill Man"
t241320 = "Young Girl (Window)"
t241321 = "Father Gascoigne (Friendly)"
t241325 = "Eileen the Crow"
t241330 = "Father Gascoigne (Boss)"
t241332 = "Older Sister (Window)"
t241334 = "Impostor Iosefka (Table)"
t241335 = "Old Woman Prototype (Clinic)"
t241350 = "(Unused)"
t241352 = "(Unused)"
t241353 = "(Unused)"
t241354 = "(Unused)"
t241355 = "(Unused)"
t241360 = "(Unused)"
t241361 = "(Unused)"
t241370 = "(Unused)"
t241371 = "(Unused)"
t241440 = "Yharnam Resident Male (Window) 1"
t241441 = "Yharnam Resident Male (Window) 2"
t241460 = "Yharnam Resident Female (Window) 1"
t241461 = "Yharnam Resident Female (Window) 2"
[maps.m24_02_00_00]
t242000 = "Upper Cathedral Ward (Lamp)"
t242001 = "Altar of Despair (Lamp)"
t242002 = "Lumenflower Gardens (Lamp)"
t242307 = "Altar of Despair"
t242480 = "Make Contact"
[maps.m25_00_00_00]
t250000 = "Forsaken Castle Cainhurst (Lamp)"
t250001 = "Vileblood Queen's Chamber (Lamp)"
t250002 = "Logarius' Seat (Lamp)"
t250300 = "Annalise (Prototype)"
t250307 = "Annalise, Queen of Castle Cainhurst"
t250308 = "Annalise (Prototype)"
t250324 = "Alfred, Hunter of Vilebloods"
[maps.m26_00_00_00]
t260000 = "Nightmare of Mensis (Lamp)"
t260001 = "Wet Nurse's Lunarium (Lamp)"
t260002 = "Mergo's Loft: Middle (Lamp)"
t260003 = "Mergo's Loft: Base (Lamp)"
t260311 = "Micolash, Host of the Nightmare"
[maps.m27_00_00_00]
t270000 = "Forbidden Woods (Lamp)"
t270001 = "Forbidden Grave (Lamp)"
t270217 = "Suspicious Beggar (Beast Form)"
t270317 = "Suspicious Beggar"
t270375 = "(Unused)"
t270465 = "Yharnam Resident Female (Window) 6"
t270503 = "Valtr, Master of the League"
[maps.m28_00_00_00]
t280000 = "Yahar'gul, Unseen Village (Lamp)"
t280001 = "Advent Plaza (Lamp)"
t280002 = "Hypogean Gaol (Lamp)"
t280003 = "Yahar'gul Chapel (Lamp)"
t280322 = "Adella, Nun of the Healing Church "
[maps.m29_00_00_00]
t290000 = "(Unused)"
t290010 = "(Unused)"
t290011 = "(Unused)"
t290012 = "(Unused)"
t290020 = "(Unused)"
t290021 = "(Unused)"
t290022 = "(Unused)"
t290110 = "Chamber of the Seal (Lamp)"
t290111 = "Layer 1 (Lamp)"
t290112 = "Layer 1: Heart (Lamp)"
t290113 = "Layer 2 (Lamp)"
t290114 = "Layer 2: Heart (Lamp)"
t290115 = "Layer 3 (Lamp)"
t290116 = "Layer 3: Heart (Lamp)"
t290117 = "Layer 4 (Lamp)"
t290118 = "Layer 4: Heart (Lamp)"
t290119 = "(Unused)"
t290300 = "Messenger Bath"
t290329 = "Patches the Spider (Shop)"
t290600 = "(Unused)"
t290601 = "(Unused)"
t290602 = "(Unused)"
[maps.m29_01_00_00]
[maps.m29_02_00_00]
[maps.m32_00_00_00]
t320000 = "Byrgenwerth (Lamp)"
t320001 = "Lecture Building (Lamp)"
t320002 = "Moonside Lake (Lamp)"
t320003 = "Lecture Building 2nd Floor (Lamp)"
t320300 = "Master Willem (Prototype)"
t320306 = "Master Willem (Prototype)"
t320310 = "Master Willem"
t320329 = "Patches the Spider"
[maps.m33_00_00_00]
t330000 = "Nightmare Frontier (Lamp)"
t330001 = "Amygdala's Chamber (Lamp)"
[maps.m34_00_00_00]
t340000 = "Hunter's Nightmare (Lamp)"
t340001 = "Nightmare Church (Lamp)"
t340002 = "Underground Corpse Pile (Lamp)"
t340003 = "Nightmare Grand Cathedral (Lamp)"
t340502 = "Father Gascoigne (Unused)"
t340504 = "Simon, Seeker of Secrets"
t340508 = "Ludwig's Head"
t340509 = "Simon, Seeker of Secrets (Corpse Pile)"
t340540 = "Bloody Corpse"
[maps.m35_00_00_00]
t350000 = "Research Hall (Lamp)"
t350001 = "Lumenwood Garden (Lamp)"
t350002 = "Astral Clocktower (Lamp)"
t350500 = "Lady Maria, of the Astral Clocktower"
t350505 = "Brador, Church Assassin"
t350506 = "Adeline, Research Hall Patient"
t350510 = "Simon, Seeker of Secrets"
t350511 = "Brador, Church Assassin (Invader)"
t350512 = "Adeline, Research Hall Patient (Head)"
t350550 = "Research Hall Patient"
t350551 = "Dying Corpse (Unused)"
t350552 = "Yamamura the Wanderer"
t350553 = "Research Hall Patient"
t350554 = "Research Hall Patient (Unused)"
t350555 = "Research Hall Patient"
t350556 = "Research Hall Patient"
t350557 = "Research Hall Patient"
t350558 = "Research Hall Patient (Unused)"
t350559 = "Dying Corpse (Unused)"
t350560 = "Fishing Hamlet Priest (Unused)"
t350561 = "(Unused)"
t350562 = "(Unused)"
t350570 = "Research Hall Patient"
t350571 = "(Unused)"
t350572 = "Research Hall Patient"
t350573 = "Research Hall Patient (Unused)"
t350574 = "Research Hall Patient (Head)"
t350575 = "Research Hall Patient (Head)"
t350576 = "(Unused)"
t350577 = "(Unused)"
t350578 = "(Unused)"
t350579 = "Research Hall Patient (Head)"
[maps.m36_00_00_00]
t360000 = "Fishing Hamlet (Lamp)"
t360001 = "Lighthouse Hut (Lamp)"
t360002 = "Coast (Lamp)"
t360507 = "Fishing Hamlet Priest"
t360511 = "Brador, Church Assassin (Unused)"
t360513 = "Simon, Seeker of Secrets"
t360514 = "Brador, Church Assassin (Invader)"
t360515 = "Brador, Church Assassin (Invader)"
t360516 = "Brador, Church Assassin (Invader)"