title = "DefaultESDDescriptions_ds3"
[maps]
[maps.m30_00_00_00]
300000 = "High Wall of Lothric Bonfire"
300001 = "Oceiros, the Consumed King Bonfire"
300002 = "Vordt of the Boreal Valley Bonfire"
300003 = "Dancer of the Boreal Valley Bonfire"
300004 = "Tower on the Wall Bonfire"
300020 = "Path of the Dragon Gesture Pickup"
300220 = "Greirat of the Undead Settlement"
300324 = "Oceiros, the Consumed King"
300330 = "Emma, High Priestess of Lothric Castle"
[maps.m30_01_00_00]
301000 = "Lothric Castle Bonfire"
301001 = "Dragonslayer Armour Bonfire"
301002 = "Dragon Barracks Bonfire"
301020 = "Altar of Sunlight"
[maps.m31_00_00_00]
310000 = "Undead Settlement Bonfire"
310001 = "Pit of Hollows Bonfire"
310002 = "Cliff Underside Bonfire"
310003 = "Dilapidated Bridge Bonfire"
310004 = "Foot of the High Wall Bonfire"
310020 = "Sacrificial Altar"
310021 = "Velka, the Goddess of Sin"
310150 = "Yoel of Londor"
310180 = "Sirris of the Sunless Realms"
310240 = "Cornyx of the Great Swamp"
310260 = "Irina of Carim"
310270 = "Eygon of Carim"
310310 = "Siegward of Catarina (lift)"
310311 = "Siegward of Caterina (ledge)"
310380 = "Talking Cage Hollow"
310410 = "Holy Knight Hodrick"
310610 = "Giant Archer"
[maps.m32_00_00_00]
320000 = "Archdragon Peak Bonfire"
320001 = "Nameless King Bonfire"
320002 = "Great Belfry Bonfire"
320003 = "Dragon-Kin Mausoleum Bonfire"
[maps.m33_00_00_00]
330000 = "Halfway Fortress Bonfire"
330001 = "Abyss Watchers Bonfire"
330002 = "Crystal Sage Bonfire"
330003 = "Farron Keep Bonfire"
330004 = "Keep Ruins Bonfire"
330005 = "Old Wolf of Farron Bonfire"
330006 = "Road of Sacrifices Bonfire"
330007 = "Crucifixion Woods Bonfire"
330008 = "Farron Keep Perimeter Bonfire"
330020 = "Old Wolf of Farron"
330170 = "Hawkwood the Deserter"
330230 = "Orbeck of Vinheim"
330290 = "Anri of Astora (male)"
330295 = "Anri of Astora (female)"
330360 = "Horace the Hushed"
[maps.m34_01_00_00]
341000 = "Twin Princes Bonfire"
341001 = "Grand Archives Bonfire"
341320 = "Lothric, Younger Prince"
[maps.m35_00_00_00]
350000 = "Cleansing Chapel Bonfire"
350001 = "Rosaria's Bed Chamber Bonfire"
350002 = "Deacons of the Deep Bonfire"
350003 = "Cathedral of the Deep Bonfire"
350020 = "Rosaria, Mother of Rebirth"
350190 = "Ringfinger Leonhard"
350300 = "Unbreakable Patches (door side 1)"
350301 = "Unbreakable Patches (Rosaria side)"
350302 = "Unbreakable Patches (door side 2)"
350310 = "Siegward of Catarina"
350510 = "Slave Knight Gael"
[maps.m37_00_00_00]
370000 = "Church of Yorshka Bonfire"
370001 = "Pontiff Sulyvahn Bonfire"
370002 = "Aldrich, Devourer of Gods Bonfire"
370003 = "Anor Londo Bonfire"
370004 = "Central Irithyll Bonfire"
370005 = "Distant Manor Bonfire"
370006 = "Water Reserve Bonfire"
370007 = "Irithyll of the Boreal Valley Bonfire"
370008 = "Prison Tower Bonfire"
370020 = "Archdeacon McDonnell"
370160 = "Company Captain Yorshka"
370180 = "Sirris of the Sunless Realms"
370190 = "Ringfinger Leonhard"
370290 = "Anri of Astora (male) (Church of Yorshka)"
370291 = "Anri of Astora (male) (Aldrich)"
370295 = "Anri of Astora (female) (Church of Yorshka)"
370296 = "Anri of Astora (female) (Aldrich)"
370310 = "Siegward of Catarina"
370400 = "Londor Assassin (Church of Yorshka)"
370401 = "Londor Assassin (Darkmoon Tomb)"
[maps.m38_00_00_00]
380000 = "High Lord Wolnir Bonfire"
380001 = "Abandoned Tomb Bonfire"
380002 = "Old King's Antechamber Bonfire"
380003 = "Demon Ruins Bonfire"
380004 = "Old Demon King Bonfire"
380005 = "Unused Bonfire"
380006 = "Catacombs of Carthus Bonfire"
380290 = "Anri of Astora (male) (upper catacombs)"
380291 = "Anri of Astora (male) (near Wolnir)"
380295 = "Anri of Astora (female) (upper catacombs)"
380296 = "Anri of Astora (female) (near Wolnir)"
[maps.m39_00_00_00]
390000 = "Irithyll Dungeon Bonfire"
390001 = "Yhorm the Giant Bonfire"
390002 = "Profaned Capital Bonfire"
390250 = "Karla"
390310 = "Siegward of Catarina (cell)"
390311 = "Siegward of Catarina (Yhorm)"
[maps.m40_00_00_00]
400000 = "Firelink Shrine Bonfire"
400001 = "Cemetery of Ash Bonfire"
400002 = "Iudex Gundyr Bonfire"
400003 = "Untended Graves Bonfire"
400004 = "Champion Gundyr Bonfire"
400120 = "Fire Keeper"
400130 = "Ludleth of Courland (alive)"
400131 = "Ludleth of Courland (ashes)"
400140 = "Yuria of Londor"
400150 = "Yoel of Londor"
400170 = "Hawkwood the Deserter (Firelink Shrine)"
400171 = "Hawkwood the Deserter (grave)"
400172 = "Legion Etiquette Gesture Pickup"
400180 = "Sirris of the Sunless Realms"
400190 = "Ringfinger Leonhard"
400200 = "Blacksmith Andre"
400210 = "Shrine Handmaid (Firelink Shrine)"
400211 = "Shrine Handmaid (Untended Graves)"
400220 = "Greirat of the Undead Settlement"
400230 = "Orbeck of Vinheim"
400240 = "Cornyx of the Great Swamp"
400250 = "Karla"
400260 = "Irina of Carim (Firelink Shrine)"
400261 = "Irina of Carim (outside)"
400262 = "Irina of Carim (fire keeper tomb)"
400270 = "Eygon of Carim (Firelink Shrine)"
400271 = "Eygon of Carim (outside)"
400290 = "Anri of Astora (male)"
400295 = "Anri of Astora (female)"
400300 = "Unbreakable Patches (lift)"
400301 = "Unbreakable Patches (Firelink Shrine)"
400360 = "Horace the Hushed"
400390 = "Pickle Pee, Pump-a-Rum"
[maps.m41_00_00_00]
410001 = "Kiln of the First Flame Bonfire"
410002 = "The First Flame"
410010 = "Flameless Shrine Bonfire"
410120 = "Fire Keeper"
410990 = "Begin New Journey Prompt"
[maps.m45_00_00_00]
450000 = "Sister Friede Bonfire"
450001 = "Snowfield Bonfire"
450002 = "Rope Bridge Cave Bonfire"
450003 = "Corvian Settlement bonfire"
450004 = "Snowy Mountain Pass Bonfire"
450005 = "Ariandel Chapel Bonfire"
450006 = "Champion's Gravetender Bonfire"
450007 = "Depths of the Painting Bonfire"
450520 = "Sir Vilhelm (Ariandel Chapel)"
450521 = "Sir Vilhelm (settlement house)"
450530 = "The Painter (settlement house)"
450531 = "The Painter (Ariandel Chapel)"
450540 = "Forlorn Corvian Settler (inside)"
450541 = "Forlorn Corvian Settler (outside)"
450550 = "Sister Friede (Ariandel Chapel)"
450551 = "Sister Friede (boss)"
450552 = "Blackflame Friede"
450560 = "Father Ariandel (passive)"
450561 = "Father Ariandel (boss)"
450590 = "Drowsy Forlorn"
[maps.m50_00_00_00]
500000 = "The Demon Prince Bonfire"
500001 = "The Dreg Heap Bonfire"
500002 = "Earthen Peak Ruins Bonfire"
500003 = "Within the Earthen Peak Ruins Bonfire"
500004 = "Unused Bonfire"
500730 = "Amnesiac Lapp (Lothric Castle ruins)"
500731 = "Amnesiac Lapp (Earthen Peak Ruins 1)"
500732 = "Amnesiac Lapp (Earthen Peak Ruins 2)"
500760 = "Stone-humped Hag"
[maps.m51_00_00_00]
510000 = "Church of Filianore Bonfire"
510001 = "Darkeater Midir Bonfire"
510002 = "Mausoleum Lookout Bonfire"
510003 = "Ringed Inner Wall Bonfire"
510004 = "Ringed City Streets Bonfire"
510005 = "Shared Grave Bonfire"
510020 = "Divine Spear Monument"
510021 = "Purging Monument"
510730 = "Amnesiac Lapp (Ringed Inner Wall)"
510731 = "Amnesiac Lapp (Above Ringed City Streets)"
510732 = "Amnesiac Lapp (near Shared Grave)"
510740 = "Shira, Knight of Filianore"
510750 = "Locust Preacher (near Ringed Inner Wall)"
510751 = "Locust Preacher (above near swamp)"
510752 = "Locust Preacher (near Ringed City Streets)"
510770 = "Pygmy Lord"
510780 = "Judicator Argo"
[maps.m51_01_00_00]
511000 = "Slave Knight Gael Bonfire"
511001 = "Filianore's Rest Bonfire"
511740 = "Shira, Knight of Filianore"
511770 = "Pygmy Lord"