title = "DefaultESDDescriptions_sdt"
[maps]
[maps.m00_00_00_00]
1 = "Sculptor's Idol"
2 = "Reflection of Strength Idol"
10 = "Eavesdrop"
11 = "Eavesdrop (Alternate)"
12 = "Remnant"
[maps.m10_00_00_00]
100210 = "Nogami Gensai"
100340 = "Lady Butterfly (Phase 1)"
100341 = "Lady Butterfly (Phase 2)"
[maps.m11_00_00_00]
110010 = "Offering Box"
110100 = "The Sculptor"
110101 = "Buddha Statue"
110102 = "Demon of Hatred"
110110 = "Remnant (Kuro and Emma)"
110111 = "Remnant (Kuro and Genichiro)"
110130 = "Hanbei the Undying"
110160 = "Inosuke Nogami's Mother"
110171 = "Anayama the Peddler"
110181 = "Inosuke Nogami"
110230 = "Emma"
110240 = "Tengu of Ashina"
110260 = "Kotaro"
110350 = "Gyobu Oniwa"
110400 = "Old Priestess"
110410 = "Crow's Bed Memorial Mob"
110420 = "Battlefield Memorial Mob"
110470 = "Fujioka the Info Broker"
110600 = "Eavesdrop (soldiers near Chained Ogre)"
110601 = "Eavesdrop (soldiers near Gyobu Oniwa)"
110602 = "Eavesdrop (soldiers after Naomori Kawarada)"
110603 = "Eavesdrop (soldier mourning his horse)"
110700 = "Injured Ashina Soldier (castle bridge)"
110701 = "Injured Red Guard (before demon warp)"