title = "DefaultMapDescriptions_er"
[maps]
m00_00_00_00 = "Common"
m10_00_00_00 = "Stormveil Castle"
m10_01_00_00 = "Chapel of Anticipation"
m11_00_00_00 = "Leyndell, Royal Capital"
m11_05_00_00 = "Leyndell, Ashen Capital"
m11_10_00_00 = "Roundtable Hold"
m12_01_00_00 = "Ainsel River"
m12_02_00_00 = "Siofra River"
m12_03_00_00 = "Deeproot Depths"
m12_04_00_00 = "Ainsel River - Boss"
m12_05_00_00 = "Mohgwyn Palace"
m12_07_00_00 = "Siofra River - Start"
m12_08_00_00 = "Siofra River - Boss"
m12_09_00_00 = "Nokron, Eternal City - Boss"
m13_00_00_00 = "Crumbling Farum Azula"
m14_00_00_00 = "Academy of Raya Lucaria"
m15_00_00_00 = "Miquella's Haligtree"
m16_00_00_00 = "Volcano Manor"
m18_00_00_00 = "Stranded Graveyard"
m19_00_00_00 = "Stone Platform"
m20_00_00_00 = "Belurat, Tower Settlement"
m20_01_00_00 = "Enir-Ilim"
m21_00_00_00 = "Shadow Keep"
m21_01_00_00 = "Specimen Storehouse"
m21_02_00_00 = "Shadow Keep - West Rampart"
m22_00_00_00 = "Stone Coffin Fissure"
m25_00_00_00 = "Finger Birthing Grounds"
m28_00_00_00 = "Midra's Manse"
m30_00_00_00 = "Tombsward Catacombs"
m30_01_00_00 = "Impaler's Catacombs"
m30_02_00_00 = "Stormfoot Catacombs"
m30_03_00_00 = "Road's End Catacombs"
m30_04_00_00 = "Murkwater Catacombs"
m30_05_00_00 = "Black Knife Catacombs"
m30_06_00_00 = "Cliffbottom Catacombs"
m30_07_00_00 = "Wyndham Catacombs"
m30_08_00_00 = "Sainted Hero's Grave"
m30_09_00_00 = "Gelmir Hero's Grave"
m30_10_00_00 = "Auriza Hero's Grave"
m30_11_00_00 = "Deathtouched Catacombs"
m30_12_00_00 = "Unsightly Catacombs"
m30_13_00_00 = "Auriza Side Tomb"
m30_14_00_00 = "Minor Erdtree Catacombs"
m30_15_00_00 = "Caelid Catacombs"
m30_16_00_00 = "War-Dead Catacombs"
m30_17_00_00 = "Giant-Conquering Hero's Grave"
m30_18_00_00 = "Giants' Mountaintop Catacombs"
m30_19_00_00 = "Consecrated Snowfield Catacombs"
m30_20_00_00 = "Hidden Path to the Haligtree"
m31_00_00_00 = "Murkwater Cave"
m31_01_00_00 = "Earthbore Cave"
m31_02_00_00 = "Tombsward Cave"
m31_03_00_00 = "Groveside Cave"
m31_04_00_00 = "Stillwater Cave"
m31_05_00_00 = "Lakeside Crystal Cave"
m31_06_00_00 = "Academy Crystal Cave"
m31_07_00_00 = "Seethewater Cave"
m31_09_00_00 = "Volcano Cave"
m31_10_00_00 = "Dragonbarrow Cave"
m31_11_00_00 = "Sellia Hideaway"
m31_12_00_00 = "Cave of the Forlorn"
m31_15_00_00 = "Coastal Cave"
m31_17_00_00 = "Highroad Cave"
m31_18_00_00 = "Perfumer's Grotto"
m31_19_00_00 = "Sage's Cave"
m31_20_00_00 = "Abandoned Cave"
m31_21_00_00 = "Gaol Cave"
m31_22_00_00 = "Spiritcaller Cave"
m32_00_00_00 = "Morne Tunnel"
m32_01_00_00 = "Limgrave Tunnels"
m32_02_00_00 = "Raya Lucaria Crystal Tunnel"
m32_04_00_00 = "Old Altus Tunnel"
m32_05_00_00 = "Altus Tunnel"
m32_07_00_00 = "Gael Tunnel"
m32_08_00_00 = "Sellia Crystal Tunnel"
m32_11_00_00 = "Yelough Anix Tunnel"
m34_10_00_00 = "Divine Tower of Limgrave"
m34_11_00_00 = "Divine Tower of Liurnia"
m34_12_00_00 = "Divine Tower of West Altus"
m34_13_00_00 = "Divine Tower of Caelid"
m34_14_00_00 = "Divine Tower of East Altus"
m34_15_00_00 = "Isolated Divine Tower"
m35_00_00_00 = "Subterranean Shunning-Grounds"
m39_20_00_00 = "Ruin-Strewn Precipice"
m40_00_00_00 = "Fog Rift Catacombs"
m40_01_00_00 = "Scorpion River Catacombs"
m40_02_00_00 = "Darklight Catacombs"
m41_00_00_00 = "Belurat Gaol"
m41_01_00_00 = "Bonny Gaol"
m41_02_00_00 = "Lamenter's Gaol"
m42_00_00_00 = "Ruined Forge Lava Intake"
m42_02_00_00 = "Ruined Forge of Starfall Past"
m42_03_00_00 = "Taylew's Ruined Forge"
m43_00_00_00 = "Rivermouth Cave"
m43_01_00_00 = "Dragon's Pit"
m45_00_00_00 = "Royal Colosseum"
m45_01_00_00 = "Caelid Colosseum"
m45_02_00_00 = "Limgrave Colosseum"
m60_00_00_00 = "Overworld"
m61_00_00_00 = "Overworld - Realm of Shadow"