title = "DefaultESDDescriptions_er"
[maps]
[maps.m00_00_00_00]
1000 = "Site of Grace"
1100 = "Alternate Site of Grace"
2000 = "Spirit Rebirth Monument"
2006 = "Old Spirit Rebirth Monument"
2012 = "Old Spirit Rebirth Monument"
3000 = "Melina"
[maps.m10_00_00_00]
20410 = "Margit, the Fell Omen"
20710 = "Godrick the Grafted"
30200 = "Gatekeeper Gostoc (gatehouse)"
30201 = "Gatekeeper Gostoc (alternate castle entrance)"
30202 = "Gatekeeper Gostoc (in the wall)"
30203 = "Gatekeeper Gostoc (lift)"
30204 = "Gatekeeper Gostoc (ontop the church)"
30205 = "Gatekeeper Gostoc (Godrick's arena)"
30206 = "Gatekeeper Gostoc (throne room)"
30220 = "Gatekeeper Gostoc (locks the door on you)"
32100 = "Kenneth Haight"
32500 = "Sorcerer Rogier"
33400 = "Nepheli Loux, Warrior (first time/throne room)"
33401 = "Nepheli Loux, Warrior (Godrick summon)"
70022 = "Commoner Ghost (below throne room)"
[maps.m11_00_00_00]
11200 = "Goldmask"
20411 = "Morgott, the Omen King (alive)"
20420 = "Morgott, the Omen King (defeated)"
22300 = "Boc the Seamster"
35100 = "Scribe Corhyn"
62000 = "Leyndell Colosseum Entry"
[maps.m11_05_00_00]
20610 = "Godfrey, First Elden Lord/Hoarah Loux, Warrior"
22300 = "Boc the Seamster"
32400 = "Sir Gideon Ofnir, the All-Knowing"
35100 = "Scribe Corhyn"
62000 = "Leyndell Colosseum Entry"
70600 = "Commoner Ghost (in the ashes)"
70601 = "Commoner Ghost (near the throne)"
[maps.m11_10_00_00]
10200 = "Finger Reader Enia"
21300 = "Smithing Master Hewg"
31400 = "Knight Diallos"
31800 = "Yura, Hunter of Bloody Fingers"
31900 = "D, Hunter of the Dead"
32000 = "Roderika, Spirit Tuner"
32200 = "Fia, Deathbed Companion"
32300 = "Dung Eater"
32400 = "Sir Gideon Ofnir, the All-Knowing"
32500 = "Sorcerer Rogier"
33400 = "Nepheli Loux, Warrior"
33900 = "Ensha of the Royal Remains"
35100 = "Scribe Corhyn"
60000 = "Twin Maiden Husks"
60800 = "Clouded Mirror Stand"
62300 = "Colosseum Entry"
[maps.m12_01_00_00]
10611 = "Renna/Ranni the Witch"
70509 = "Commoner Ghost"
80128 = "Hermit Merchant"
[maps.m12_02_00_00]
21600 = "Blaidd the Half-Wolf"
21800 = "Asimi"
31920 = "D, Beholder of Death"
70503 = "Commoner Ghost"
80127 = "Abandoned Merchant"
[maps.m12_03_00_00]
10160 = "Godwyn's Wet Nurse"
31920 = "D, Beholder of Death"
32200 = "Fia, Deathbed Companion"
60300 = "Walking Mausoleum"
70506 = "Wandering Noble Ghost (on high tower)"
70508 = "Noble Ghost (on lower tower)"
[maps.m12_05_00_00]
20910 = "Mohg, Lord of Blood"
30101 = "White Mask Varré (Outside)"
30110 = "White Mask Varré (Cavern)"
70504 = "Commoner Ghost"
80129 = "Imprisoned Merchant"
[maps.m12_07_00_00]
21800 = "Asimi"
[maps.m13_00_00_00]
20210 = "Beast Clergyman/Maliketh (Underground)"
20211 = "Beast Clergyman/Maliketh (Above Ground)"
22000 = "Alexander, Warrior Jar"
[maps.m14_00_00_00]
20000 = "Rennala, Queen of the Full Moon (NPC)"
20010 = "Rennala, Queen of the Full Moon (Phase 1)"
20011 = "Rennala, Queen of the Full Moon (Phase 2)"
22300 = "Boc the Seamster"
31200 = "Witch-Hunter Jerren (Outside Arena)"
31210 = "Witch-Hunter Jerren (Inside Arena)"
31621 = "Sorceress Sellen (Middle Arena 1)"
31630 = "Sorceress Sellen (Ball)"
31640 = "Sorceress Sellen (Middle Arena 2)"
[maps.m15_00_00_00]
20310 = "Malenia, Blade of Miquella"
34800 = "Millicent (Elphael Entrance/Inside Tree)"
34820 = "Millicent (Other Inside Tree)"
[maps.m16_00_00_00]
21410 = "Rykard, Lord of Blashpemy"
30000 = "Tanith, Volcano Manor Proprietress"
30900 = "Patches the Untethered"
31300 = "Rya the Scout"
31400 = "Knight Diallos"
32600 = "Recusant Bernahl"
32610 = "Sword of Bernahl"
33200 = "Rykard-Hating Ghost"
[maps.m18_00_00_00]
70602 = "Commoner Ghost"
[maps.m19_00_00_00]
60700 = "Corpse of Radagon/Marika"
[maps.m30_02_00_00]
70000 = "Commoner Ghost"
[maps.m31_00_00_00]
30900 = "Patches the Untethered"
[maps.m31_11_00_00]
11000 = "Primeval Sorcerer Lusat"
[maps.m31_15_00_00]
22300 = "Demi-Human Boc"
[maps.m32_07_00_00]
22000 = "Alexander, Warrior Jar"
[maps.m34_11_00_00]
70109 = "Wandering Noble Ghost"
[maps.m35_00_00_00]
31000 = "Finger Maiden Hyetta"
32300 = "Dung Eater"
[maps.m60_00_00_00]
10100 = "Finger Reader Crone (Stormhill)"
10120 = "Finger Reader Crone (Bellum Highway)"
10123 = "Finger Reader Crone (Academy Gate Town)"
10130 = "Finger Reader Crone (Forest-Spanning Greatbridge)"
10131 = "Finger Reader Crone (Capital Outskirts)"
10140 = "Finger Reader Crone (South of Caelem Ruins)"
10150 = "Keeper of Forbidden Lands"
10600 = "Renna/Ranni the Witch (Church of Elleh)"
10601 = "Renna/Ranni the Witch (Ranni's Rise)"
11100 = "Primeval Sorcerer Azur"
11200 = "Goldmask"
20200 = "Gurrang, Beast Clergyman"
20400 = "Morgott, the Omen King"
20900 = "Mohg, Lord of Blood"
21300 = "Smithing Master Hewg"
21600 = "Blaidd the Half-Wolf (Redmane Castle)"
21601 = "Blaidd the Half-Wolf (Ranni's Rise)"
21900 = "Old Albus"
22000 = "Alexander, Warrior Jar (Saintsbridge/Redmane Castle/Radahn's Arena)"
22100 = "Large Living Jar"
22300 = "Boc the Seamster"
22400 = "War Counselor Iji (Road to Caria Manor)"
22420 = "War Counselor Iji (Ranni's Rise)"
22600 = "Jar Bairn"
22700 = "Aurelia"
30100 = "White Mask Varré"
30700 = "Preceptor Seluvis (Seluvis's Rise)"
30703 = "Preceptor Seluvis (Center of Seluvis's Rise)"
30710 = "Pidia, Carian Servant"
30730 = "Preceptor Seluvis (Ranni's Rise)"
30900 = "Patches the Untethered"
31000 = "Lightseeker Hyetta (Lake-Facing Cliffs/Purified Ruins)"
31100 = "Morne Castellan Edgar"
31200 = "Castellan Jerren (Castle Redmane/Witchbane Ruins)"
31300 = "Rya the Scout"
31400 = "Knight Diallos"
31600 = "Sorceress Sellen (Waypoint Ruins)"
31610 = "Sorceress Sellen (Witchbane Ruins)"
31900 = "D, Hunter of Death"
32000 = "Roderika, Spirit Tuner"
32100 = "Kenneth Haight"
32300 = "Dung Eater"
32600 = "Knight Bernahl"
33000 = "Miriel, Pastor of Vows"
33001 = "Basin of Atonement"
33100 = "Blackguard Big Boggart (Boilprawn Shack/Capital Outskirts)"
33300 = "Sorcerer Thops"
33400 = "Nepheli Loux, Warrior"
33500 = "Rico"
34800 = "Millicent"
34900 = "Sage Gowry"
35100 = "Scribe Corhyn"
36300 = "Finger Maiden Therolina"
60100 = "Church of Dragon Communion"
60101 = "Cathedral of Dragon Communion"
60200 = "Smithing Table"
60300 = "Walking Masoleum (Weeping Peninsula)"
60301 = "Walking Masoleum (Near Raya Lucaria Crystal Tunnel)"
60302 = "Walking Masoleum (Near Castle Sol)"
60303 = "Walking Masoleum (Consecrated Snowfield)"
60320 = "Walking Masoleum (South of Masoleum Compound)"
60321 = "Walking Masoleum (North of Masoleum Compound)"
61000 = "Grand Lift of Rold"
80000 = "Merchant Kalé"
80111 = "Nomadic Merchant (East of Saintsbridge)"
80112 = "Nomadic Merchant (Near Mistwood and Fort Haight)"
80113 = "Nomadic Merchant (Near Coastal Cave)"
80114 = "Nomadic Merchant (Castle Morne Rampart)"
80115 = "Nomadic Merchant (Liurnia Lake Shore)"
80116 = "Isolated Merchant (Shack in Weeping Peninsula)"
80117 = "Isolated Merchant (South Raya Lucaria Gate Path)"
80118 = "Nomadic Merchant (Near Bellum Church)"
80119 = "Hermit Merchant (Capital Outskirts)"
80120 = "Nomadic Merchant (Forest-Spanning Greatbridge)"
80121 = "Nomadic Merchant (Mt. Gelmir Cliffside)"
80122 = "Nomadic Merchant (Near Aeonia Swamp Shore)"
80123 = "Nomadic Merchant (Southern Caelid Highway)"
80125 = "Isolated Merchant (Shack in Greyoll's Dragonbarrow)"
80126 = "Hermit Merchant (South of Stargazers' Ruins)"