title = "DefaultESDDescriptions_er"
[maps]
[maps.m00_00_00_00]
t000001000 = "Site of Grace"
t000001100 = "Alternate Site of Grace"
t000002000 = "Spirit Rebirth Monument"
t000002006 = "Old Spirit Rebirth Monument"
t000002012 = "Old Spirit Rebirth Monument"
t000003000 = "Melina"
[maps.m10_00_00_00]
t204101000 = "Margit, the Fell Omen"
t207101000 = "Godrick the Grafted"
t302001000 = "Gatekeeper Gostoc (gatehouse)"
t302011000 = "Gatekeeper Gostoc (alternate castle entrance)"
t302021000 = "Gatekeeper Gostoc (in the wall)"
t302031000 = "Gatekeeper Gostoc (lift)"
t302041000 = "Gatekeeper Gostoc (ontop the church)"
t302051000 = "Gatekeeper Gostoc (Godrick's arena)"
t302061000 = "Gatekeeper Gostoc (throne room)"
t302201000 = "Gatekeeper Gostoc (locks the door on you)"
t321001000 = "Kenneth Haight"
t325001000 = "Sorcerer Rogier"
t334001000 = "Nepheli Loux, Warrior (first time/throne room)"
t334011000 = "Nepheli Loux, Warrior (Godrick summon)"
t700221000 = "Commoner Ghost (below throne room)"
[maps.m11_00_00_00]
t112001100 = "Goldmask"
t204111100 = "Morgott, the Omen King (alive)"
t204201100 = "Morgott, the Omen King (defeated)"
t223001100 = "Boc the Seamster"
t351001100 = "Scribe Corhyn"
t620001100 = "Leyndell Colosseum Entry"
[maps.m11_05_00_00]
t206101105 = "Godfrey, First Elden Lord/Hoarah Loux, Warrior"
t223001105 = "Boc the Seamster"
t324001105 = "Sir Gideon Ofnir, the All-Knowing"
t351001105 = "Scribe Corhyn"
t620001105 = "Leyndell Colosseum Entry"
t706001105 = "Commoner Ghost (in the ashes)"
t706011105 = "Commoner Ghost (near the throne)"
[maps.m11_10_00_00]
t102001110 = "Finger Reader Enia"
t213001110 = "Smithing Master Hewg"
t314001110 = "Knight Diallos"
t318001110 = "Yura, Hunter of Bloody Fingers"
t319001110 = "D, Hunter of the Dead"
t320001110 = "Roderika, Spirit Tuner"
t322001110 = "Fia, Deathbed Companion"
t323001110 = "Dung Eater"
t324001110 = "Sir Gideon Ofnir, the All-Knowing"
t325001110 = "Sorcerer Rogier"
t334001110 = "Nepheli Loux, Warrior"
t339001110 = "Ensha of the Royal Remains"
t351001110 = "Scribe Corhyn"
t600001110 = "Twin Maiden Husks"
t608001110 = "Clouded Mirror Stand"
t623001110 = "Colosseum Entry"
[maps.m12_01_00_00]
t106111201 = "Renna/Ranni the Witch"
t705091201 = "Commoner Ghost"
t801281201 = "Hermit Merchant"
[maps.m12_02_00_00]
t216001202 = "Blaidd the Half-Wolf"
t218001202 = "Asimi"
t319201202 = "D, Beholder of Death"
t705031202 = "Commoner Ghost"
t801271202 = "Abandoned Merchant"
[maps.m12_03_00_00]
t101601203 = "Godwyn's Wet Nurse"
t319201203 = "D, Beholder of Death"
t322001203 = "Fia, Deathbed Companion"
t603001203 = "Walking Mausoleum"
t705061203 = "Wandering Noble Ghost (on high tower)"
t705081203 = "Noble Ghost (on lower tower)"
[maps.m12_05_00_00]
t209101205 = "Mohg, Lord of Blood"
t301011205 = "White Mask Varré (Outside)"
t301101205 = "White Mask Varré (Cavern)"
t705041205 = "Commoner Ghost"
t801291205 = "Imprisoned Merchant"
[maps.m12_07_00_00]
t218001207 = "Asimi"
[maps.m13_00_00_00]
t202101300 = "Beast Clergyman/Maliketh (Underground)"
t202111300 = "Beast Clergyman/Maliketh (Above Ground)"
t220001300 = "Alexander, Warrior Jar"
[maps.m14_00_00_00]
t200001400 = "Rennala, Queen of the Full Moon (NPC)"
t200101400 = "Rennala, Queen of the Full Moon (Phase 1)"
t200111400 = "Rennala, Queen of the Full Moon (Phase 2)"
t223001400 = "Boc the Seamster"
t312001400 = "Witch-Hunter Jerren (Outside Arena)"
t312101400 = "Witch-Hunter Jerren (Inside Arena)"
t316211400 = "Sorceress Sellen (Middle Arena 1)"
t316301400 = "Sorceress Sellen (Ball)"
t316401400 = "Sorceress Sellen (Middle Arena 2)"
[maps.m15_00_00_00]
t203101500 = "Malenia, Blade of Miquella"
t348001500 = "Millicent (Elphael Entrance/Inside Tree)"
t348201500 = "Millicent (Other Inside Tree)"
[maps.m16_00_00_00]
t214101600 = "Rykard, Lord of Blashpemy"
t300001600 = "Tanith, Volcano Manor Proprietress"
t309001600 = "Patches the Untethered"
t313001600 = "Rya the Scout"
t314001600 = "Knight Diallos"
t326001600 = "Recusant Bernahl"
t326101600 = "Sword of Bernahl"
t332001600 = "Rykard-Hating Ghost"
[maps.m18_00_00_00]
t706021800 = "Commoner Ghost"
[maps.m19_00_00_00]
t607001900 = "Corpse of Radagon/Marika"
[maps.m30_02_00_00]
t700003002 = "Commoner Ghost"
[maps.m31_00_00_00]
t309003100 = "Patches the Untethered"
[maps.m31_11_00_00]
t110003111 = "Primeval Sorcerer Lusat"
[maps.m31_15_00_00]
t223003115 = "Demi-Human Boc"
[maps.m32_07_00_00]
t220003207 = "Alexander, Warrior Jar"
[maps.m34_11_00_00]
t701093411 = "Wandering Noble Ghost"
[maps.m35_00_00_00]
t310003500 = "Finger Maiden Hyetta"
t323003500 = "Dung Eater"
[maps.m60_00_00_00]
t101006000 = "Finger Reader Crone (Stormhill)"
t101206000 = "Finger Reader Crone (Bellum Highway)"
t101236000 = "Finger Reader Crone (Academy Gate Town)"
t101306000 = "Finger Reader Crone (Forest-Spanning Greatbridge)"
t101316000 = "Finger Reader Crone (Capital Outskirts)"
t101406000 = "Finger Reader Crone (South of Caelem Ruins)"
t101506000 = "Keeper of Forbidden Lands"
t106006000 = "Renna/Ranni the Witch (Church of Elleh)"
t106016000 = "Renna/Ranni the Witch (Ranni's Rise)"
t111006000 = "Primeval Sorcerer Azur"
t112006000 = "Goldmask"
t202006000 = "Gurrang, Beast Clergyman"
t204006000 = "Morgott, the Omen King"
t209006000 = "Mohg, Lord of Blood"
t213006000 = "Smithing Master Hewg"
t216006000 = "Blaidd the Half-Wolf (Redmane Castle)"
t216016000 = "Blaidd the Half-Wolf (Ranni's Rise)"
t219006000 = "Old Albus"
t220006000 = "Alexander, Warrior Jar (Saintsbridge/Redmane Castle/Radahn's Arena)"
t221006000 = "Large Living Jar"
t223006000 = "Boc the Seamster"
t224006000 = "War Counselor Iji (Road to Caria Manor)"
t224206000 = "War Counselor Iji (Ranni's Rise)"
t226006000 = "Jar Bairn"
t227006000 = "Aurelia"
t301006000 = "White Mask Varré"
t307006000 = "Preceptor Seluvis (Seluvis's Rise)"
t307036000 = "Preceptor Seluvis (Center of Seluvis's Rise)"
t307106000 = "Pidia, Carian Servant"
t307306000 = "Preceptor Seluvis (Ranni's Rise)"
t309006000 = "Patches the Untethered"
t310006000 = "Lightseeker Hyetta (Lake-Facing Cliffs/Purified Ruins)"
t311006000 = "Morne Castellan Edgar"
t312006000 = "Castellan Jerren (Castle Redmane/Witchbane Ruins)"
t313006000 = "Rya the Scout"
t314006000 = "Knight Diallos"
t316006000 = "Sorceress Sellen (Waypoint Ruins)"
t316106000 = "Sorceress Sellen (Witchbane Ruins)"
t319006000 = "D, Hunter of Death"
t320006000 = "Roderika, Spirit Tuner"
t321006000 = "Kenneth Haight"
t323006000 = "Dung Eater"
t326006000 = "Knight Bernahl"
t330006000 = "Miriel, Pastor of Vows"
t330016000 = "Basin of Atonement"
t331006000 = "Blackguard Big Boggart (Boilprawn Shack/Capital Outskirts)"
t333006000 = "Sorcerer Thops"
t334006000 = "Nepheli Loux, Warrior"
t335006000 = "Rico"
t348006000 = "Millicent"
t349006000 = "Sage Gowry"
t351006000 = "Scribe Corhyn"
t363006000 = "Finger Maiden Therolina"
t601006000 = "Church of Dragon Communion"
t601016000 = "Cathedral of Dragon Communion"
t602006000 = "Smithing Table"
t603006000 = "Walking Masoleum (Weeping Peninsula)"
t603016000 = "Walking Masoleum (Near Raya Lucaria Crystal Tunnel)"
t603026000 = "Walking Masoleum (Near Castle Sol)"
t603036000 = "Walking Masoleum (Consecrated Snowfield)"
t603206000 = "Walking Masoleum (South of Masoleum Compound)"
t603216000 = "Walking Masoleum (North of Masoleum Compound)"
t610006000 = "Grand Lift of Rold"
t800006000 = "Merchant Kalé"
t801116000 = "Nomadic Merchant (East of Saintsbridge)"
t801126000 = "Nomadic Merchant (Near Mistwood and Fort Haight)"
t801136000 = "Nomadic Merchant (Near Coastal Cave)"
t801146000 = "Nomadic Merchant (Castle Morne Rampart)"
t801156000 = "Nomadic Merchant (Liurnia Lake Shore)"
t801166000 = "Isolated Merchant (Shack in Weeping Peninsula)"
t801176000 = "Isolated Merchant (South Raya Lucaria Gate Path)"
t801186000 = "Nomadic Merchant (Near Bellum Church)"
t801196000 = "Hermit Merchant (Capital Outskirts)"
t801206000 = "Nomadic Merchant (Forest-Spanning Greatbridge)"
t801216000 = "Nomadic Merchant (Mt. Gelmir Cliffside)"
t801226000 = "Nomadic Merchant (Near Aeonia Swamp Shore)"
t801236000 = "Nomadic Merchant (Southern Caelid Highway)"
t801256000 = "Isolated Merchant (Shack in Greyoll's Dragonbarrow)"
t801266000 = "Hermit Merchant (South of Stargazers' Ruins)"