title = "DefaultESDDescriptions_sdt"
[maps]
[maps.m00_00_00_00]
1 = "Sculptor's Idol"
2 = "Reflection of Strength Idol"
10 = "Eavesdrop"
11 = "Eavesdrop (Alternate)"
12 = "Remnant"
[maps.m10_00_00_00]
210 = "Nogami Gensai"
340 = "Lady Butterfly (Phase 1)"
341 = "Lady Butterfly (Phase 2)"
[maps.m11_00_00_00]
10 = "Offering Box"
100 = "The Sculptor"
101 = "Buddha Statue"
102 = "Demon of Hatred"
110 = "Remnant (Kuro and Emma)"
111 = "Remnant (Kuro and Genichiro)"
130 = "Hanbei the Undying"
160 = "Inosuke Nogami's Mother"
171 = "Anayama the Peddler"
181 = "Inosuke Nogami"
230 = "Emma"
240 = "Tengu of Ashina"
260 = "Kotaro"
350 = "Gyobu Oniwa"
400 = "Old Priestess"
410 = "Crow's Bed Memorial Mob"
420 = "Battlefield Memorial Mob"
470 = "Fujioka the Info Broker"
600 = "Eavesdrop (soldiers near Chained Ogre)"
601 = "Eavesdrop (soldiers near Gyobu Oniwa)"
602 = "Eavesdrop (soldiers after Naomori Kawarada)"
603 = "Eavesdrop (soldier mourning his horse)"
700 = "Injured Ashina Soldier (castle bridge)"
701 = "Injured Red Guard (before demon warp)"