title = "DefaultESDDescriptions_er"
[maps]
[maps.m00_00_00_00]
1000 = "Site of Grace"
1100 = "Alternate Site of Grace"
2000 = "Spirit Rebirth Monument"
2006 = "Old Spirit Rebirth Monument"
2012 = "Old Spirit Rebirth Monument"
3000 = "Melina"
[maps.m10_00_00_00]
204101000 = "Margit, the Fell Omen"
207101000 = "Godrick the Grafted"
302001000 = "Gatekeeper Gostoc (gatehouse)"
302011000 = "Gatekeeper Gostoc (alternate castle entrance)"
302021000 = "Gatekeeper Gostoc (in the wall)"
302031000 = "Gatekeeper Gostoc (lift)"
302041000 = "Gatekeeper Gostoc (ontop the church)"
302051000 = "Gatekeeper Gostoc (Godrick's arena)"
302061000 = "Gatekeeper Gostoc (throne room)"
302201000 = "Gatekeeper Gostoc (locks the door on you)"
321001000 = "Kenneth Haight"
325001000 = "Sorcerer Rogier"
334001000 = "Nepheli Loux, Warrior (first time/throne room)"
334011000 = "Nepheli Loux, Warrior (Godrick summon)"
700221000 = "Commoner Ghost (below throne room)"
[maps.m11_00_00_00]
112001100 = "Goldmask"
204111100 = "Morgott, the Omen King (alive)"
204201100 = "Morgott, the Omen King (defeated)"
223001100 = "Boc the Seamster"
351001100 = "Scribe Corhyn"
620001100 = "Leyndell Colosseum Entry"
[maps.m11_05_00_00]
206101105 = "Godfrey, First Elden Lord/Hoarah Loux, Warrior"
223001105 = "Boc the Seamster"
324001105 = "Sir Gideon Ofnir, the All-Knowing"
351001105 = "Scribe Corhyn"
620001105 = "Leyndell Colosseum Entry"
706001105 = "Commoner Ghost (in the ashes)"
706011105 = "Commoner Ghost (near the throne)"
[maps.m11_10_00_00]
102001110 = "Finger Reader Enia"
213001110 = "Smithing Master Hewg"
314001110 = "Knight Diallos"
318001110 = "Yura, Hunter of Bloody Fingers"
319001110 = "D, Hunter of the Dead"
320001110 = "Roderika, Spirit Tuner"
322001110 = "Fia, Deathbed Companion"
323001110 = "Dung Eater"
324001110 = "Sir Gideon Ofnir, the All-Knowing"
325001110 = "Sorcerer Rogier"
334001110 = "Nepheli Loux, Warrior"
339001110 = "Ensha of the Royal Remains"
351001110 = "Scribe Corhyn"
600001110 = "Twin Maiden Husks"
608001110 = "Clouded Mirror Stand"
623001110 = "Colosseum Entry"
[maps.m12_01_00_00]
106111201 = "Renna/Ranni the Witch"
705091201 = "Commoner Ghost"
801281201 = "Hermit Merchant"
[maps.m12_02_00_00]
216001202 = "Blaidd the Half-Wolf"
218001202 = "Asimi"
319201202 = "D, Beholder of Death"
705031202 = "Commoner Ghost"
801271202 = "Abandoned Merchant"
[maps.m12_03_00_00]
101601203 = "Godwyn's Wet Nurse"
319201203 = "D, Beholder of Death"
322001203 = "Fia, Deathbed Companion"
603001203 = "Walking Mausoleum"
705061203 = "Wandering Noble Ghost (on high tower)"
705081203 = "Noble Ghost (on lower tower)"
[maps.m12_05_00_00]
209101205 = "Mohg, Lord of Blood"
301011205 = "White Mask Varré (Outside)"
301101205 = "White Mask Varré (Cavern)"
705041205 = "Commoner Ghost"
801291205 = "Imprisoned Merchant"
[maps.m12_07_00_00]
218001207 = "Asimi"
[maps.m13_00_00_00]
202101300 = "Beast Clergyman/Maliketh (Underground)"
202111300 = "Beast Clergyman/Maliketh (Above Ground)"
220001300 = "Alexander, Warrior Jar"
[maps.m14_00_00_00]
200001400 = "Rennala, Queen of the Full Moon (NPC)"
200101400 = "Rennala, Queen of the Full Moon (Phase 1)"
200111400 = "Rennala, Queen of the Full Moon (Phase 2)"
223001400 = "Boc the Seamster"
312001400 = "Witch-Hunter Jerren (Outside Arena)"
312101400 = "Witch-Hunter Jerren (Inside Arena)"
316211400 = "Sorceress Sellen (Middle Arena 1)"
316301400 = "Sorceress Sellen (Ball)"
316401400 = "Sorceress Sellen (Middle Arena 2)"
[maps.m15_00_00_00]
203101500 = "Malenia, Blade of Miquella"
348001500 = "Millicent (Elphael Entrance/Inside Tree)"
348201500 = "Millicent (Other Inside Tree)"
[maps.m16_00_00_00]
214101600 = "Rykard, Lord of Blashpemy"
300001600 = "Tanith, Volcano Manor Proprietress"
309001600 = "Patches the Untethered"
313001600 = "Rya the Scout"
314001600 = "Knight Diallos"
326001600 = "Recusant Bernahl"
326101600 = "Sword of Bernahl"
332001600 = "Rykard-Hating Ghost"
[maps.m18_00_00_00]
706021800 = "Commoner Ghost"
[maps.m19_00_00_00]
607001900 = "Corpse of Radagon/Marika"
[maps.m30_02_00_00]
700003002 = "Commoner Ghost"
[maps.m31_00_00_00]
309003100 = "Patches the Untethered"
[maps.m31_11_00_00]
110003111 = "Primeval Sorcerer Lusat"
[maps.m31_15_00_00]
223003115 = "Demi-Human Boc"
[maps.m32_07_00_00]
220003207 = "Alexander, Warrior Jar"
[maps.m34_11_00_00]
701093411 = "Wandering Noble Ghost"
[maps.m35_00_00_00]
310003500 = "Finger Maiden Hyetta"
323003500 = "Dung Eater"
[maps.m60_00_00_00]
101006000 = "Finger Reader Crone (Stormhill)"
101206000 = "Finger Reader Crone (Bellum Highway)"
101236000 = "Finger Reader Crone (Academy Gate Town)"
101306000 = "Finger Reader Crone (Forest-Spanning Greatbridge)"
101316000 = "Finger Reader Crone (Capital Outskirts)"
101406000 = "Finger Reader Crone (South of Caelem Ruins)"
101506000 = "Keeper of Forbidden Lands"
106006000 = "Renna/Ranni the Witch (Church of Elleh)"
106016000 = "Renna/Ranni the Witch (Ranni's Rise)"
111006000 = "Primeval Sorcerer Azur"
112006000 = "Goldmask"
202006000 = "Gurrang, Beast Clergyman"
204006000 = "Morgott, the Omen King"
209006000 = "Mohg, Lord of Blood"
213006000 = "Smithing Master Hewg"
216006000 = "Blaidd the Half-Wolf (Redmane Castle)"
216016000 = "Blaidd the Half-Wolf (Ranni's Rise)"
219006000 = "Old Albus"
220006000 = "Alexander, Warrior Jar (Saintsbridge/Redmane Castle/Radahn's Arena)"
221006000 = "Large Living Jar"
223006000 = "Boc the Seamster"
224006000 = "War Counselor Iji (Road to Caria Manor)"
224206000 = "War Counselor Iji (Ranni's Rise)"
226006000 = "Jar Bairn"
227006000 = "Aurelia"
301006000 = "White Mask Varré"
307006000 = "Preceptor Seluvis (Seluvis's Rise)"
307036000 = "Preceptor Seluvis (Center of Seluvis's Rise)"
307106000 = "Pidia, Carian Servant"
307306000 = "Preceptor Seluvis (Ranni's Rise)"
309006000 = "Patches the Untethered"
310006000 = "Lightseeker Hyetta (Lake-Facing Cliffs/Purified Ruins)"
311006000 = "Morne Castellan Edgar"
312006000 = "Castellan Jerren (Castle Redmane/Witchbane Ruins)"
313006000 = "Rya the Scout"
314006000 = "Knight Diallos"
316006000 = "Sorceress Sellen (Waypoint Ruins)"
316106000 = "Sorceress Sellen (Witchbane Ruins)"
319006000 = "D, Hunter of Death"
320006000 = "Roderika, Spirit Tuner"
321006000 = "Kenneth Haight"
323006000 = "Dung Eater"
326006000 = "Knight Bernahl"
330006000 = "Miriel, Pastor of Vows"
330016000 = "Basin of Atonement"
331006000 = "Blackguard Big Boggart (Boilprawn Shack/Capital Outskirts)"
333006000 = "Sorcerer Thops"
334006000 = "Nepheli Loux, Warrior"
335006000 = "Rico"
348006000 = "Millicent"
349006000 = "Sage Gowry"
351006000 = "Scribe Corhyn"
363006000 = "Finger Maiden Therolina"
601006000 = "Church of Dragon Communion"
601016000 = "Cathedral of Dragon Communion"
602006000 = "Smithing Table"
603006000 = "Walking Masoleum (Weeping Peninsula)"
603016000 = "Walking Masoleum (Near Raya Lucaria Crystal Tunnel)"
603026000 = "Walking Masoleum (Near Castle Sol)"
603036000 = "Walking Masoleum (Consecrated Snowfield)"
603206000 = "Walking Masoleum (South of Masoleum Compound)"
603216000 = "Walking Masoleum (North of Masoleum Compound)"
610006000 = "Grand Lift of Rold"
800006000 = "Merchant Kalé"
801116000 = "Nomadic Merchant (East of Saintsbridge)"
801126000 = "Nomadic Merchant (Near Mistwood and Fort Haight)"
801136000 = "Nomadic Merchant (Near Coastal Cave)"
801146000 = "Nomadic Merchant (Castle Morne Rampart)"
801156000 = "Nomadic Merchant (Liurnia Lake Shore)"
801166000 = "Isolated Merchant (Shack in Weeping Peninsula)"
801176000 = "Isolated Merchant (South Raya Lucaria Gate Path)"
801186000 = "Nomadic Merchant (Near Bellum Church)"
801196000 = "Hermit Merchant (Capital Outskirts)"
801206000 = "Nomadic Merchant (Forest-Spanning Greatbridge)"
801216000 = "Nomadic Merchant (Mt. Gelmir Cliffside)"
801226000 = "Nomadic Merchant (Near Aeonia Swamp Shore)"
801236000 = "Nomadic Merchant (Southern Caelid Highway)"
801256000 = "Isolated Merchant (Shack in Greyoll's Dragonbarrow)"
801266000 = "Hermit Merchant (South of Stargazers' Ruins)"