title = "DefaultESDDescriptions_bb"
[maps]
[maps.m21_00_00_00]
210000 = "Yharnam Headstone"
210001 = "Frontier Headstone"
210002 = "Unseen Headstone"
210003 = "Nightmare Headstone"
210010 = "(Unused)"
210020 = "(Unused)"
210030 = "(Unused)"
210040 = "(Unused)"
210050 = "Makeshift Altar"
210060 = "First Ritual Altar"
210070 = "Second Ritual Altar"
210080 = "Third Ritual Altar"
210090 = "Fourth Ritual Altar"
210100 = "Fifth Ritual Altar"
210110 = "Final Ritual Altar"
210140 = "(Unused)"
210141 = "(Unused)"
210200 = "(Unused)"
210304 = "Plain Doll"
210305 = "Gherman (Wheelchair Bound)"
210306 = "Gherman (Boss)"
210600 = "DS1 Undead Shopkeeper (Unused)"
210610 = "(Unused)"
210611 = "(Unused)"
210612 = "(Unused)"
210613 = "(Unused)"
210614 = "(Unused)"
210615 = "(Unused)"
210616 = "(Unused)"
210617 = "(Unused)"
210618 = "(Unused)"
210619 = "(Unused)"
210630 = "(Unused)"
210631 = "(Unused)"
210632 = "(Unused)"
210633 = "(Unused)"
210634 = "(Unused)"
210635 = "(Unused)"
210650 = "(Unused)"
210690 = "(Unused)"
210691 = "Bath Messenger Shop"
210692 = "Workshop"
210693 = "Storage Chest"
210694 = "Starting Gift Messengers 1"
210695 = "Starting Gift Messengers 2"
210696 = "Change Appearance Mirror (Unused)"
210697 = "Messenger Stump"
210698 = "Insight Messenger Shop"
210699 = "Memory Altar"
210700 = "Plain Doll Prototype"
210701 = "(Unused)"
210702 = "(Unused)"
210703 = "(Unused)"
210704 = "(Unused)"
210705 = "(Unused)"
210706 = "(Unused)"
210710 = "(Unused)"
210711 = "(Unused)"
210712 = "(Unused)"
210713 = "(Unused)"
210714 = "(Unused)"
210715 = "(Unused)"
210716 = "(Unused)"
210720 = "Messenger Gift Notebook"
210721 = "Hunter's Nightmare Headstone"
210900 = "(Unused)"
[maps.m21_01_00_00]
211000 = "Abandoned Old Workshop (Lamp)"
[maps.m22_00_00_00]
220000 = "Hemwick Charnel Lane (Lamp)"
220001 = "Watches Abode (Lamp)"
220300 = "Micolash (Prototype)"
220307 = "Micolash (Prototype) 2"
220374 = "(Unused)"
220464 = "Yharnam Resident Female (Window) 5"
[maps.m23_00_00_00]
230000 = "Old Yharnam (Lamp)"
230001 = "Church of the Good Chalice (Lamp)"
230002 = "Graveyard of the Darkbeast (Lamp)"
230300 = "Old Yharnam Survivor (Unused)"
230323 = "Djura"
[maps.m24_00_00_00]
240000 = "Cathedral Ward (Lamp)"
240001 = "Grand Cathedral (Lamp)"
240002 = "Lamp (Unused)"
240003 = "Lamp (Unused)"
240118 = "(Unused)"
240215 = "Bigoted Old Man (Home)"
240217 = "Suspicious Beggar (Beast Form)"
240218 = "Arianna, Woman of Pleasure (Home)"
240312 = "Chapel Dweller"
240315 = "Bigoted Old Man (Chapel)"
240316 = "Lonely Old Dear"
240317 = "Afflicted Beggar (Unused)"
240318 = "Arianna, Woman of Pleasure (Chapel)"
240322 = "Adella, Nun of the Healing Church"
240325 = "Eileen the Crow"
240326 = "Vicar Amelia (Prayer)"
240327 = "Gatekeeper to the Forbidden Woods"
240333 = "Alfred, Hunter of Vilebloods (Old Yharnam Side)"
240334 = "Adella, Nun of the Healing Church (Blood Moon)"
240335 = "Arianna, Woman of Pleasure (Blood Moon)"
240336 = "Arianna, Woman of Pleasure (Blood Moon post One Reborn)"
240337 = "Arianna, Woman of Pleasure (Birth/Unused)"
240338 = "Afflicted Beggar"
240339 = "Adella, Nun of the Healing Church (Killed Arianna/Night)"
240340 = "Adella, Nun of the Healing Church (Killed Arianna/Blood Moon)"
240341 = "Eileen the Crow (Hostile at the Church)"
240342 = "Eileen the Crow (Dying on the stairs)"
240343 = "Alfred, Hunter of Vilebloods (Forbidden Woods Side)"
240351 = "(Unused)"
240353 = "(Unused)"
240362 = "(Unused)"
240363 = "(Unused)"
240364 = "(Unused)"
240372 = "(Unused)"
240373 = "(Unused)"
240442 = "Yharnam Resident Male (Window) 3"
240443 = "Yharnam Resident Male (Window) 4"
240444 = "Yharnam Resident Male (Window) 5"
240462 = "Yharnam Resident Female (Window) 3"
240463 = "Yharnam Resident Female (Window) 4"
240504 = "Chapel Dweller (Unused)"
240630 = "(Unused)"
240700 = "(Unused)"
[maps.m24_01_00_00]
241000 = "1st Floor Sickroom (Lamp)"
241001 = "Central Yharnam (Lamp)"
241002 = "Great Bridge (Lamp)"
241003 = "Tomb of Oedon (Lamp)"
241190 = "(Unused)"
241300 = "Father Gascoigne Alpha (Boss)"
241310 = "Father Gascoigne Alpha (Boss)"
241313 = "Iosefka"
241314 = "Impostor Iosefka (Behind the door)"
241315 = "Bigoted Old Man (Unused)"
241316 = "Lonely Old Dear (Window)"
241318 = "Arianna, Woman of Pleasure (Birth)"
241319 = "Gilbert, Critically Ill Man"
241320 = "Young Girl (Window)"
241321 = "Father Gascoigne (Friendly)"
241325 = "Eileen the Crow"
241330 = "Father Gascoigne (Boss)"
241332 = "Older Sister (Window)"
241334 = "Impostor Iosefka (Table)"
241335 = "Old Woman Prototype (Clinic)"
241350 = "(Unused)"
241352 = "(Unused)"
241353 = "(Unused)"
241354 = "(Unused)"
241355 = "(Unused)"
241360 = "(Unused)"
241361 = "(Unused)"
241370 = "(Unused)"
241371 = "(Unused)"
241440 = "Yharnam Resident Male (Window) 1"
241441 = "Yharnam Resident Male (Window) 2"
241460 = "Yharnam Resident Female (Window) 1"
241461 = "Yharnam Resident Female (Window) 2"
[maps.m24_02_00_00]
242000 = "Upper Cathedral Ward (Lamp)"
242001 = "Altar of Despair (Lamp)"
242002 = "Lumenflower Gardens (Lamp)"
242307 = "Altar of Despair"
242480 = "Make Contact"
[maps.m25_00_00_00]
250000 = "Forsaken Castle Cainhurst (Lamp)"
250001 = "Vileblood Queen's Chamber (Lamp)"
250002 = "Logarius' Seat (Lamp)"
250300 = "Annalise (Prototype)"
250307 = "Annalise, Queen of Castle Cainhurst"
250308 = "Annalise (Prototype)"
250324 = "Alfred, Hunter of Vilebloods"
[maps.m26_00_00_00]
260000 = "Nightmare of Mensis (Lamp)"
260001 = "Wet Nurse's Lunarium (Lamp)"
260002 = "Mergo's Loft: Middle (Lamp)"
260003 = "Mergo's Loft: Base (Lamp)"
260311 = "Micolash, Host of the Nightmare"
[maps.m27_00_00_00]
270000 = "Forbidden Woods (Lamp)"
270001 = "Forbidden Grave (Lamp)"
270217 = "Suspicious Beggar (Beast Form)"
270317 = "Suspicious Beggar"
270375 = "(Unused)"
270465 = "Yharnam Resident Female (Window) 6"
270503 = "Valtr, Master of the League"
[maps.m28_00_00_00]
280000 = "Yahar'gul, Unseen Village (Lamp)"
280001 = "Advent Plaza (Lamp)"
280002 = "Hypogean Gaol (Lamp)"
280003 = "Yahar'gul Chapel (Lamp)"
280322 = "Adella, Nun of the Healing Church "
[maps.m29_00_00_00]
290000 = "(Unused)"
290010 = "(Unused)"
290011 = "(Unused)"
290012 = "(Unused)"
290020 = "(Unused)"
290021 = "(Unused)"
290022 = "(Unused)"
290110 = "Chamber of the Seal (Lamp)"
290111 = "Layer 1 (Lamp)"
290112 = "Layer 1: Heart (Lamp)"
290113 = "Layer 2 (Lamp)"
290114 = "Layer 2: Heart (Lamp)"
290115 = "Layer 3 (Lamp)"
290116 = "Layer 3: Heart (Lamp)"
290117 = "Layer 4 (Lamp)"
290118 = "Layer 4: Heart (Lamp)"
290119 = "(Unused)"
290300 = "Messenger Bath"
290329 = "Patches the Spider (Shop)"
290600 = "(Unused)"
290601 = "(Unused)"
290602 = "(Unused)"
[maps.m29_01_00_00]
[maps.m29_02_00_00]
[maps.m32_00_00_00]
320000 = "Byrgenwerth (Lamp)"
320001 = "Lecture Building (Lamp)"
320002 = "Moonside Lake (Lamp)"
320003 = "Lecture Building 2nd Floor (Lamp)"
320300 = "Master Willem (Prototype)"
320306 = "Master Willem (Prototype)"
320310 = "Master Willem"
320329 = "Patches the Spider"
[maps.m33_00_00_00]
330000 = "Nightmare Frontier (Lamp)"
330001 = "Amygdala's Chamber (Lamp)"
[maps.m34_00_00_00]
340000 = "Hunter's Nightmare (Lamp)"
340001 = "Nightmare Church (Lamp)"
340002 = "Underground Corpse Pile (Lamp)"
340003 = "Nightmare Grand Cathedral (Lamp)"
340502 = "Father Gascoigne (Unused)"
340504 = "Simon, Seeker of Secrets"
340508 = "Ludwig's Head"
340509 = "Simon, Seeker of Secrets (Corpse Pile)"
340540 = "Bloody Corpse"
[maps.m35_00_00_00]
350000 = "Research Hall (Lamp)"
350001 = "Lumenwood Garden (Lamp)"
350002 = "Astral Clocktower (Lamp)"
350500 = "Lady Maria, of the Astral Clocktower"
350505 = "Brador, Church Assassin"
350506 = "Adeline, Research Hall Patient"
350510 = "Simon, Seeker of Secrets"
350511 = "Brador, Church Assassin (Invader)"
350512 = "Adeline, Research Hall Patient (Head)"
350550 = "Research Hall Patient"
350551 = "Dying Corpse (Unused)"
350552 = "Yamamura the Wanderer"
350553 = "Research Hall Patient"
350554 = "Research Hall Patient (Unused)"
350555 = "Research Hall Patient"
350556 = "Research Hall Patient"
350557 = "Research Hall Patient"
350558 = "Research Hall Patient (Unused)"
350559 = "Dying Corpse (Unused)"
350560 = "Fishing Hamlet Priest (Unused)"
350561 = "(Unused)"
350562 = "(Unused)"
350570 = "Research Hall Patient"
350571 = "(Unused)"
350572 = "Research Hall Patient"
350573 = "Research Hall Patient (Unused)"
350574 = "Research Hall Patient (Head)"
350575 = "Research Hall Patient (Head)"
350576 = "(Unused)"
350577 = "(Unused)"
350578 = "(Unused)"
350579 = "Research Hall Patient (Head)"
[maps.m36_00_00_00]
360000 = "Fishing Hamlet (Lamp)"
360001 = "Lighthouse Hut (Lamp)"
360002 = "Coast (Lamp)"
360507 = "Fishing Hamlet Priest"
360511 = "Brador, Church Assassin (Unused)"
360513 = "Simon, Seeker of Secrets"
360514 = "Brador, Church Assassin (Invader)"
360515 = "Brador, Church Assassin (Invader)"
360516 = "Brador, Church Assassin (Invader)"