title = "DefaultESDNames_DS3"
[m30_00_00_00]
0 = "High Wall of Lothric Bonfire"
1 = "Oceiros, the Consumed King Bonfire"
2 = "Vordt of the Boreal Valley Bonfire"
3 = "Dancer of the Boreal Valley Bonfire"
4 = "Tower on the Wall Bonfire"
20 = "Path of the Dragon Gesture Pickup"
220 = "Greirat of the Undead Settlement"
324 = "Oceiros, the Consumed King"
330 = "Emma, High Priestess of Lothric Castle"
[m30_01_00_00]
0 = "Lothric Castle Bonfire"
1 = "Dragonslayer Armour Bonfire"
2 = "Dragon Barracks Bonfire"
20 = "Altar of Sunlight"
[m31_00_00_00]
0 = "Undead Settlement Bonfire"
1 = "Pit of Hollows Bonfire"
2 = "Cliff Underside Bonfire"
3 = "Dilapidated Bridge Bonfire"
4 = "Foot of the High Wall Bonfire"
20 = "Sacrificial Altar"
21 = "Velka, the Goddess of Sin"
150 = "Yoel of Londor"
180 = "Sirris of the Sunless Realms"
240 = "Cornyx of the Great Swamp"
260 = "Irina of Carim"
270 = "Eygon of Carim"
310 = "Siegward of Catarina (lift)"
311 = "Siegward of Caterina (ledge)"
380 = "Talking Cage Hollow"
410 = "Holy Knight Hodrick"
610 = "Giant Archer"
[m32_00_00_00]
0 = "Archdragon Peak Bonfire"
1 = "Nameless King Bonfire"
2 = "Great Belfry Bonfire"
3 = "Dragon-Kin Mausoleum Bonfire"
[m33_00_00_00]
0 = "Halfway Fortress Bonfire"
1 = "Abyss Watchers Bonfire"
2 = "Crystal Sage Bonfire"
3 = "Farron Keep Bonfire"
4 = "Keep Ruins Bonfire"
5 = "Old Wolf of Farron Bonfire"
6 = "Road of Sacrifices Bonfire"
7 = "Crucifixion Woods Bonfire"
8 = "Farron Keep Perimeter Bonfire"
20 = "Old Wolf of Farron"
170 = "Hawkwood the Deserter"
230 = "Orbeck of Vinheim"
290 = "Anri of Astora (male)"
295 = "Anri of Astora (female)"
360 = "Horace the Hushed"
[m34_01_00_00]
0 = "Twin Princes Bonfire"
1 = "Grand Archives Bonfire"
320 = "Lothric, Younger Prince"
[m35_00_00_00]
0 = "Cleansing Chapel Bonfire"
1 = "Rosaria's Bed Chamber Bonfire"
2 = "Deacons of the Deep Bonfire"
3 = "Cathedral of the Deep Bonfire"
20 = "Rosaria, Mother of Rebirth"
190 = "Ringfinger Leonhard"
300 = "Unbreakable Patches (door side 1)"
301 = "Unbreakable Patches (Rosaria side)"
302 = "Unbreakable Patches (door side 2)"
310 = "Siegward of Catarina"
510 = "Slave Knight Gael"
[m37_00_00_00]
0 = "Church of Yorshka Bonfire"
1 = "Pontiff Sulyvahn Bonfire"
2 = "Aldrich, Devourer of Gods Bonfire"
3 = "Anor Londo Bonfire"
4 = "Central Irithyll Bonfire"
5 = "Distant Manor Bonfire"
6 = "Water Reserve Bonfire"
7 = "Irithyll of the Boreal Valley Bonfire"
8 = "Prison Tower Bonfire"
20 = "Archdeacon McDonnell"
160 = "Company Captain Yorshka"
180 = "Sirris of the Sunless Realms"
190 = "Ringfinger Leonhard"
290 = "Anri of Astora (male) (Church of Yorshka)"
291 = "Anri of Astora (male) (Aldrich)"
295 = "Anri of Astora (female) (Church of Yorshka)"
296 = "Anri of Astora (female) (Aldrich)"
310 = "Siegward of Catarina"
400 = "Londor Assassin (Church of Yorshka)"
401 = "Londor Assassin (Darkmoon Tomb)"
[m38_00_00_00]
0 = "High Lord Wolnir Bonfire"
1 = "Abandoned Tomb Bonfire"
2 = "Old King's Antechamber Bonfire"
3 = "Demon Ruins Bonfire"
4 = "Old Demon King Bonfire"
5 = "Unused Bonfire"
6 = "Catacombs of Carthus Bonfire"
290 = "Anri of Astora (male) (upper catacombs)"
291 = "Anri of Astora (male) (near Wolnir)"
295 = "Anri of Astora (female) (upper catacombs)"
296 = "Anri of Astora (female) (near Wolnir)"
[m39_00_00_00]
0 = "Irithyll Dungeon Bonfire"
1 = "Yhorm the Giant Bonfire"
2 = "Profaned Capital Bonfire"
250 = "Karla"
310 = "Siegward of Catarina (cell)"
311 = "Siegward of Catarina (Yhorm)"
[m40_00_00_00]
0 = "Firelink Shrine Bonfire"
1 = "Cemetery of Ash Bonfire"
2 = "Iudex Gundyr Bonfire"
3 = "Untended Graves Bonfire"
4 = "Champion Gundyr Bonfire"
120 = "Fire Keeper"
130 = "Ludleth of Courland (alive)"
131 = "Ludleth of Courland (ashes)"
140 = "Yuria of Londor"
150 = "Yoel of Londor"
170 = "Hawkwood the Deserter (Firelink Shrine)"
171 = "Hawkwood the Deserter (grave)"
172 = "Legion Etiquette Gesture Pickup"
180 = "Sirris of the Sunless Realms"
190 = "Ringfinger Leonhard"
200 = "Blacksmith Andre"
210 = "Shrine Handmaid (Firelink Shrine)"
211 = "Shrine Handmaid (Untended Graves)"
220 = "Greirat of the Undead Settlement"
230 = "Orbeck of Vinheim"
240 = "Cornyx of the Great Swamp"
250 = "Karla"
260 = "Irina of Carim (Firelink Shrine)"
261 = "Irina of Carim (outside)"
262 = "Irina of Carim (fire keeper tomb)"
270 = "Eygon of Carim (Firelink Shrine)"
271 = "Eygon of Carim (outside)"
290 = "Anri of Astora (male)"
295 = "Anri of Astora (female)"
300 = "Unbreakable Patches (lift)"
301 = "Unbreakable Patches (Firelink Shrine)"
360 = "Horace the Hushed"
390 = "Pickle Pee, Pump-a-Rum"
[m41_00_00_00]
1 = "Kiln of the First Flame Bonfire"
2 = "The First Flame"
10 = "Flameless Shrine Bonfire"
120 = "Fire Keeper"
990 = "Begin New Journey Prompt"
[m45_00_00_00]
0 = "Sister Friede Bonfire"
1 = "Snowfield Bonfire"
2 = "Rope Bridge Cave Bonfire"
3 = "Corvian Settlement bonfire"
4 = "Snowy Mountain Pass Bonfire"
5 = "Ariandel Chapel Bonfire"
6 = "Champion's Gravetender Bonfire"
7 = "Depths of the Painting Bonfire"
520 = "Sir Vilhelm (Ariandel Chapel)"
521 = "Sir Vilhelm (settlement house)"
530 = "The Painter (settlement house)"
531 = "The Painter (Ariandel Chapel)"
540 = "Forlorn Corvian Settler (inside)"
541 = "Forlorn Corvian Settler (outside)"
550 = "Sister Friede (Ariandel Chapel)"
551 = "Sister Friede (boss)"
552 = "Blackflame Friede"
560 = "Father Ariandel (passive)"
561 = "Father Ariandel (boss)"
590 = "Drowsy Forlorn"
[m50_00_00_00]
0 = "The Demon Prince Bonfire"
1 = "The Dreg Heap Bonfire"
2 = "Earthen Peak Ruins Bonfire"
3 = "Within the Earthen Peak Ruins Bonfire"
4 = "Unused Bonfire"
730 = "Amnesiac Lapp (Lothric Castle ruins)"
731 = "Amnesiac Lapp (Earthen Peak Ruins 1)"
732 = "Amnesiac Lapp (Earthen Peak Ruins 2)"
760 = "Stone-humped Hag"
[m51_00_00_00]
0 = "Church of Filianore Bonfire"
1 = "Darkeater Midir Bonfire"
2 = "Mausoleum Lookout Bonfire"
3 = "Ringed Inner Wall Bonfire"
4 = "Ringed City Streets Bonfire"
5 = "Shared Grave Bonfire"
20 = "Divine Spear Monument"
21 = "Purging Monument"
730 = "Amnesiac Lapp (Ringed Inner Wall)"
731 = "Amnesiac Lapp (Above Ringed City Streets)"
732 = "Amnesiac Lapp (near Shared Grave)"
740 = "Shira, Knight of Filianore"
750 = "Locust Preacher (near Ringed Inner Wall)"
751 = "Locust Preacher (above near swamp)"
752 = "Locust Preacher (near Ringed City Streets)"
770 = "Pygmy Lord"
780 = "Judicator Argo"
[m51_01_00_00]
0 = "Slave Knight Gael Bonfire"
1 = "Filianore's Rest Bonfire"
740 = "Shira, Knight of Filianore"
770 = "Pygmy Lord"